### ISSUE TITLE
Error when install via composer

### ISSUE THREAD

**Issue by unglevan** [dmstr/yii2-adminlte-asset#10]
Problem 1
    - Installation request for dmstr/yii2-adminlte-asset * -> satisfiable by dmstr/yii2-adminlte-asset[0.1.0].
    - dmstr/yii2-adminlte-asset 0.1.0 requires bower-asset/admin-lte * -> no matching package found.

It work on mac. but not in server ubuntu @@

**Comment by schmunk42** [comment]
Do you have beta4 of the fxp/composer-asset-plugin installed?

**Comment by unglevan** [comment]
no i dont.
So i need install 
composer require fxp/composer-asset-plugin *
before run
composer require dmstr/yii2-adminlte-asset *
right?

**Comment by schmunk42** [comment]
Globally like so

     composer global require "fxp/composer-asset-plugin:1.0.0-beta4"

**Comment by unglevan** [comment]
got other error

```
 Problem 1
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1].
```

here is my config

```
 "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "dmstr/yii2-adminlte-asset": "*",
        "omgdef/yii2-multilingual-behavior": "*"
    },
```

**Comment by unglevan** [comment]
Thanks man. I cached in vendor. Its work when I removed it and installed again.

**Comment by schmunk42** [comment]
So this issue can be closed?

**Comment by unglevan** [comment]
i have other problem. How can run `composer global require "fxp/composer-asset-plugin:1.0.0-beta4"`
in elastic beanstalk?
core: PHP

**Comment by schmunk42** [comment]
I haven't tried it on Elastic Beanstalk yet, but this [SO answer](http://stackoverflow.com/a/17528576/291573) looks useful. You may also have a look at the [cloud deployment](http://phundament.com/docs/50-deploy.md) section in the docs, just some inspiration.

**Comment by germanliu** [comment]
Hi @unglevan where you able to run composer global require "fxp/composer-asset-plugin:1.0.0-beta4" in elastic beanstalk? I'm running through the same problem. Thanks
