### ISSUE TITLE
Class 'dmstr\web\AdminLteAsset' not found

### ISSUE THREAD

**Issue by jeansusgodney** [dmstr/yii2-adminlte-asset#102]
I'm trying to get the admin template work, but I keep getting the following error: 

PHP Fatal Error – yii\base\ErrorException

Class 'dmstr\web\AdminLteAsset' not found

 in C:\xampp\htdocs\project\advanced\backend\views\layouts\main.php at line 25
```
    dmstr\web\AdminLteAsset::register($this);
 
```

Additional info:
PHP Version 5.6.15

Thanks in advance

**Comment by schmunk42** [comment]
Check your autoloading paths (case-sensivity also!), did you install the extension via composer?

For debugging you can try to set an alias like `'@dmstr/web' => '@vendor/dmstr/yii2-adminlte-asset/web'`.

**Comment by githubjeka** [comment]
Must be `\dmstr\web\AdminLteAsset::register($this);`

**Comment by jeansusgodney** [comment]
Hei guys, solved.
I was working on Windows environment, I thought unzipping the file was enough. 
I finally started over by installing via composer and it worked. 

Thanks for the help guys.

**Comment by rpm-16** [comment]
hi all have same problem... on remote host. Sombebody know how to fix it without using composer?

**Comment by schmunk42** [comment]
> hi all have same problem... on remote host. Sombebody know how to fix it without using composer?

see https://github.com/dmstr/yii2-adminlte-asset/issues/102#issuecomment-260644159
