### ISSUE TITLE
Missing CSS for dataTable

### ISSUE THREAD

**Issue by mikehaertl** [dmstr/yii2-adminlte-asset#103]
I tried to use LTE's data tables as described here:

https://almsaeedstudio.com/themes/AdminLTE/pages/tables/data.html

The use classes like `.dataTables_paginate` but it seems the related CSS is not included in the extension. The class is defined in AdminLTE here:

https://github.com/almasaeed2010/AdminLTE/blob/master/plugins/datatables/dataTables.bootstrap.css

So is this supported? Or am I missing something?

**Comment by schmunk42** [comment]
Plugins are currently not supported out-of-the-box. 

Do you have any idea how we should include them? Maybe a adding separate AssetBundle `AdminLtePlugins` ... or even separate ones for each plugin?

CC: @githubjeka

**Comment by githubjeka** [comment]
DataTables is a plug-in for the jQuery Javascript library. https://datatables.net/
In my projects I don't like to use php-widgets for javascripts libraries. I always use native js code from a library.

**Comment by schmunk42** [comment]
Let's keep that open for a while...

**Comment by mikehaertl** [comment]
@githubjeka This is not about the functional features of data tables. I just want to use the styles. They are mentioned in the LTE documentation but are not included in their minified CSS file. I also could not find any hint that you need to manually include the CSS from the plugin to make this work - which I found confusing.

@schmunk42 Yes, maybe an additional asset would make sense. As this is mostly used in admin backends, size shouldn't really matter, so I'd bundle everything into one asset.

**Comment by githubjeka** [comment]
Ok.

You can create an DataTablesAssetBundle and set `sourcePath` like as [here](https://github.com/dmstr/yii2-adminlte-asset/blob/master/web/AdminLteAsset.php#L13)
```
public $sourcePath = '@vendor/almasaeed2010/adminlte/plugins/datatables';
```

**Comment by mikehaertl** [comment]
@githubjeka Why not include the asset in this extension?

**Comment by githubjeka** [comment]
Plugins too much and some of them are outdated.

**Comment by mikehaertl** [comment]
Hmm. I think, at least all the examples listed in AdminLTE's documentation should work out of the box. Most of the developers that use AdminLTE do this, because they want a quick solution that just works. It quite irritating if you again have to spend time figuring out the missing parts. Even more so because AdminLTE's documentation does not mention this anywhere.

So basically this is a problem of unclear docs on AdminLTE's site. But still it's easy to fix, if we bundle everything in another asset.

**Comment by mikehaertl** [comment]
The example plugin asset can be simplified:

* The only dependency is the asset of this extension here
* It could also include Js/CSS for other plugins

```php
use yii\web\AssetBundle;

/**
 * This asset adds plugin CSS to the AdminLTE asset
 */
class AdminLtePluginAsset extends AssetBundle
{
    public $sourcePath = '@vendor/almasaeed2010/adminlte/plugins';
    public $js = [
        'datatables/dataTables.bootstrap.min.js',
        // more plugin Js here
    ];
    public $css = [
        'datatables/dataTables.bootstrap.css',
        // more plugin CSS here
    ];
    public $depends = [
        'dmstr\web\AdminLteAsset',
    ];
}
```

**Comment by githubjeka** [comment]
Look good.
Please send PR

**Comment by mikehaertl** [comment]
@githubjeka Done
