### ISSUE TITLE
Unable to install using composer

### ISSUE THREAD

**Issue by machour** [dmstr/yii2-adminlte-asset#11]
When I run:
>   php composer.phar require dmstr/yii2-adminlte-asset "*"

I get:

> Reading bower.json of bower-asset/admin-lte (v1.2.1)
> Importing tag v1.2.1 (1.2.1.0)
>                                                                                                                    
>  [InvalidArgumentException]                                                                                           
>  No driver found to handle Asset VCS repository > http://omnipotent.net/jquery.sparkline/2.1.2/jquery.sparkline.min.js

**Comment by machour** [comment]
My mistake, just saw this ticket : https://github.com/dmstr/yii2-adminlte-asset/issues/7

Closing, sorry for the noise.

**Comment by schmunk42** [comment]
No problem! If you have a template for your Yii2 Application like Phundament with Docker you can avoid most of these common problems.
See http://phundament.com/docs/51-fig.md
