### ISSUE TITLE
left.php show wrong `fa fa icon`

### ISSUE THREAD

**Issue by bubifengyun** [dmstr/yii2-adminlte-asset#110]
## Problem
I use `composer update` all to the latest, but I find that, 

```php
'icon' => 'fa fa user'
```
in the layout, left.php it will show wrong icon as flag, and any `fa fa-****` show wrong icon as flag. but in header.php every `fa fa-***`  will show the true icon.

## Solution
Then, I downgrade AdminLTE, it still show wrong icon as 'flag'. I upgrade the AdminLTE to the latest. I downgrade your `yii2-adminlte-asset` to old one, the `fa fa-***` give true icon. 

## I think
Very sorry that, i cannot tell you the exact version, Old one's version may be `2.0.x-dev` show in composer.json. And the date is `Jul 28, 2016`. Any Problem?Thank you

**Comment by veronicavg** [comment]
I found the same issue

**Comment by Quexer69** [comment]
Have a look at this:

https://github.com/dmstr/yii2-adminlte-asset/commit/b34bdc251df6ceeecab6eebf129e5cc58d233944

The icon prefix will be set bei the menu widget since https://github.com/dmstr/yii2-adminlte-asset/commit/b34bdc251df6ceeecab6eebf129e5cc58d233944. So you can choose which icon library you are using and just pass the icon name.

I updated the example views for you.

Available in [2.4.1](https://github.com/dmstr/yii2-adminlte-asset/releases/tag/2.4.1)

**Comment by veronicavg** [comment]
Ok thanks!

`'icon' => 'comments-o',`

**Comment by bubifengyun** [comment]
@Quexer69 I think it may be not a good solution. The former version, you input `fa fa-xxx`, now, you input `xxx`, in the *left.php*. If you want to show icon in *header.php*, you must input `fa fa-xxx` again.  Can it return to the old format? Thank you.

**Comment by Quexer69** [comment]
@bubifengyun I think its a good solution because it allows you to use any icon package you want with the menu widget!

You refer to the header.php view which is a simple and only hardcoded example.
I dont see any disadvantages. What issues are you facing exactly in your dev workflow?

**Comment by bubifengyun** [comment]
@Quexer69 I return to old version. It works well now, so I do not want to upgrade to the newest. Thanks for your improvement.

**Comment by vbazovic** [comment]
@bubifengyun you can set static variable before calling a widget in yii2 like this:
`dmstr\widgets\Menu::$iconClassPrefix = ''; `
and use the newest version

**Comment by tokiaquino** [comment]
@Quexer69 whats if i want  use both package on the same menu?

**Comment by Quexer69** [comment]
@tokiaquino simply add this `dmstr\widgets\Menu::$iconClassPrefix = '';` before you call the menu widget - as vbazovic already mentioned above.

Then just pass the full icon class you want to use...

- `glyphicon glyphicon-home`
- `fa fa-home`
- `icon icon-home`
- ...

see https://github.com/dmstr/yii2-adminlte-asset/blob/master/widgets/Menu.php#L79

**Comment by zuicis** [comment]
Fa 5.xx prefix changed. 

Solid:fas	(<i class="fas fa-camera-retro">)
Regular:far	(<i class="far fa-camera-retro">)	
Light:fal 	(<i class="fal fa-camera-retro">)	
Brands: fab (<i class="fab fa-font-awesome">)

**Comment by Quexer69** [comment]
@zuicis PR‘s to support the new FontAwesome 5 icon class prefixes are welcome.
