### ISSUE TITLE
make yii2 gridview more stand out

### ISSUE THREAD

**Issue by michaelnguyen547** [dmstr/yii2-adminlte-asset#111]
Yii2 GridView kind of blend in with the background color. Any suggestions to fix the issue ?

![gridview](https://cloud.githubusercontent.com/assets/436950/24884787/52cf9ade-1e08-11e7-9055-9f54efa79747.png)

**Comment by schmunk42** [comment]
I usually put form elements in boxes or panels.

**Comment by michaelnguyen547** [comment]
wow, thanks for a great tip. It does make GridView prettier. thanks for your plugin.

![2017-04-10_1621](https://cloud.githubusercontent.com/assets/436950/24885102/e42aed2a-1e09-11e7-92aa-165bd2106fac.png)

**Comment by schmunk42** [comment]
Pro-Tipp ;)

Create a box layout, like so: https://github.com/dmstr/yii2-backend-module/blob/master/src/views/layouts/box.php

And use it in the module config: https://github.com/dmstr/phd5-app/blob/master/src/config/common.php#L276

Most modules need no further tweaks, see phd for examples.
