### ISSUE TITLE
Menu widget fails to detect active menu item

### ISSUE THREAD

**Issue by Demak** [dmstr/yii2-adminlte-asset#113]
Hello, there seems to be a problem with isItemActive widget menu method, it fails to detect active menu item. As far as I understand, the problem is in controller id on line 192:
`$route = ltrim(Yii::$app->controller->module->getUniqueId() . '/' . $route, '/');`
I am using this theme with basic application template, my controller is inherited from yii\web\Controller and in its module property I have an instance of yii\web\Application, getUniqueId of which returns an empty string, so for example for item `['label' => 'Homepage', 'icon' => 'home','url' => ['homepage']]`
which resolves to 'admin/homepage' in $this->route, $route will be just 'homepage' and doesn't match.
If I remove module and try to use just `$route = ltrim(Yii::$app->controller->getUniqueId() . '/' . $route, '/');` it works perfect. Am I missing some configuration option?

**Comment by schmunk42** [comment]
How do your routes look like? Are they in the app-frontend or backend or module?

**Comment by dimd4** [comment]
Hey. I also have a problem after the update.
Menu widget fails to detect active menu item.

For example:
In the backend.
For the route "/articles" all ok,
And for /articles/update/8 or /articles/create fails.

On the version of yii2-adminlte-asset (2.3.4) everything worked correctly.

And why should You add a prefix for icons ($ iconClassPrefix = 'fa fa-';)? 
Everything worked fine, but now i need to remove the "fa-fa" everywhere.

I had to roll back to the previous version.

My parameters:
Yii2 ver 2.0.11.2
Dmstr / yii2-adminlte-asset ":" 2.4.2 "

I apologize for my English.

**Comment by Quexer69** [comment]
@dimd4 please see #110

**Comment by Demak** [comment]
I am using basic app template, with usual controller AdminController, inherited from yii\web\Controller, without module. There is no custom routing rules for this controller in urlManager configuration, there are some for SiteController, but they are quite straightforward and I am sure they can't influence other controller. All problematic routes are relative to the current controller:
'url' => ['homepage'] does not get recognized, while
'url' => ['/admin/homepage'] works

**Comment by Demak** [comment]
As a fix I have created a wrapper and overridden isItemActive, getting ID from controller instead of module, now routes are working, but that probably will not work for module controller routes.

**Comment by Demak** [comment]
I have created a basic yii2 setup to demonstrate problem: [https://github.com/Demak/LTEProblemExample](url)
on test and test2 actions menu does not have active item, on test3 it is active

**Comment by dev3k** [comment]
i have some how similar issue, i have 'url'=> ['/category'], isItemActive detect /category but not /category/create

**Comment by hoaaah** [comment]
When we use module. This code return only module name.
```
Yii::$app->controller->module->getUniqueId()
```
This code return module name and controller name.
```
Yii::$app->controller->getUniqueId()
```
It make 'active' only applied at action index, but don't applied at other action in controller, though both return same value in action index and other action.

**Comment by crestoff** [comment]
I have removed all @alias'es from template - and all works fine now!
before: @admin/user
now:    Yii::getAlias('@admin') . '/user'

**Comment by crestoff** [comment]
I'm found solution:
before:
```
        $posDefaultAction = strpos($this->route, Yii::$app->controller->defaultAction);
        if ($posDefaultAction) {
            $this->noDefaultAction = rtrim(substr($this->route, 0, $posDefaultAction), '/');
        } else {
            $this->noDefaultAction = false;
        }

```
after:
```
        $posDefaultAction = strpos($this->route, Yii::$app->controller->action->id);
        if ($posDefaultAction) {
            $this->noDefaultAction = rtrim(substr($this->route, 0, $posDefaultAction), '/');
        } else {
            $this->noDefaultAction = false;
        }
```

**Comment by dimd4** [comment]
crestoff, thanks, it works for me.

**Comment by schmunk42** [comment]
Added various test-routes in https://github.com/dmstr/yii2-adminlte-asset/commit/6f75ab8a6f1137d7253505a41e234994cb577e68

Please provide a URL example which fails if there's still an issue.

**Comment by krissss** [comment]
@schmunk42 This problem is still alive. 

```php
$items = [
   [
        'label' => 'parent', 'icon' => 'list', 'url' => '#',
        'items' => [
            ['label' => 'sub1', 'icon' => 'circle-o', 'url' => ['/category']],
        ]
    ],
]
```

I have `'url'=> ['/category']`, `isItemActive` detect `/category` but not `/category/create` or `/category/update`.

There is no custom routing rules for this controller in urlManager configuration, And no module.

@crestoff solution can work, but still no PR.
