### ISSUE TITLE
How to use Top Nav Layout

### ISSUE THREAD

**Issue by FaizalAmiruddinR2** [dmstr/yii2-adminlte-asset#116]
How to use Top Nav Layout based on https://adminlte.io/themes/AdminLTE/pages/layout/top-nav.html ?

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/27067044-42e738b2-5011-11e7-83b9-3d9433f91748.png)

**Comment by FaizalAmiruddinR2** [comment]
Okay, so there are no any widgets or configurations for the menu like left.php in layout?

**Comment by githubjeka** [comment]
No, welcome to Pull Request

**Comment by FaizalAmiruddinR2** [comment]
Okay, Thanks
