### ISSUE TITLE
Failed to Install with composer on Version 2.4.2

### ISSUE THREAD

**Issue by azuharu** [dmstr/yii2-adminlte-asset#119]
Hi, I tried to install using command **composer require dmstr/yii2-adminlte-asset "2.*"** but it give me this error

>  [Composer\Repository\InvalidRepositoryException]
>   No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load
>   a package from it.

then I changed it using 2.4.1 and its worked.

Please look for it
Thank you

**Comment by schmunk42** [comment]
Duplicate of https://github.com/dmstr/yii2-adminlte-asset/issues/118

**Comment by schmunk42** [comment]
Please see https://github.com/dmstr/yii2-adminlte-asset/issues/133#issuecomment-337179853
