### ISSUE TITLE
No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.

### ISSUE THREAD

**Issue by kucheriavij** [dmstr/yii2-adminlte-asset#123]
I install with the component of the `php composer.phar command requires dmstr/yii2-adminlte-asset "2. *"`. Returns `
[Composer\Repository\InvalidRepositoryException]
   No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.
`

**Comment by githubjeka** [comment]
What is command? `php composer.phar command  ... `

https://getcomposer.org/doc/03-cli.md

**Comment by githubjeka** [comment]
We don't use your provided code `DmitryBaranovskiy/eve.git`

https://github.com/dmstr/yii2-adminlte-asset/blob/master/composer.json#L17-L23

**Comment by kucheriavij** [comment]
Can be taken from dependencies?

**Comment by githubjeka** [comment]
https://github.com/almasaeed2010/AdminLTE/search?utf8=%E2%9C%93&q=DmitryBaranovskiy&type=
Need investigate

**Comment by kucheriavij** [comment]
https://github.com/DmitryBaranovskiy/raphael/search?utf8=%E2%9C%93&q=eve&type=
There is a dependence

**Comment by githubjeka** [comment]
Update composer and [fxp/composer-asset-plugin](https://github.com/fxpio/composer-asset-plugin) and try again.

All works fine
![image](https://user-images.githubusercontent.com/874234/29304316-fdc45b8c-819a-11e7-9554-02ef59a3c8c5.png)

**Comment by schmunk42** [comment]
I really wonder where this is coming from, see also https://github.com/dmstr/yii2-adminlte-asset/issues/118 and https://github.com/dmstr/yii2-adminlte-asset/issues/119

@francoispluchino Any idea?

**Comment by francoispluchino** [comment]
Because https://github.com/DmitryBaranovskiy/eve return 404 page not found... So, the `eve` package registred in the [Bower Regsitry](https://bower.io/search) isn't valid.

**Comment by araviaravi** [comment]
Adding VCS repository bower-asset/eve-raphael
Reading bower.json of bower-asset/eve-raphael (v0.5.0)
Importing tag v0.5.0 (0.5.0.0)
Adding VCS repository bower-asset/eve

                                                                               
  [Composer\Repository\InvalidRepositoryException]                             
  No valid bower.json was found in any branch or tag of https://github.com/Dm  
  itryBaranovskiy/eve.git, could not load a package from it.                   
                                                                               

Exception trace:
 () at /home/aravind/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:44
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:185
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at /home/aravind/.composer/vendor/fxp/composer-asset-plugin/Repository/Util.php:71
 Fxp\Composer\AssetPlugin\Repository\Util::addRepositoryInstance() at /home/aravind/.composer/vendor/fxp/composer-asset-plugin/Repository/Util.php:44
 Fxp\Composer\AssetPlugin\Repository\Util::addRepository() at /home/aravind/.composer/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.php:141
 Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:161
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:273
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromJobs() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:324
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:214
 Composer\DependencyResolver\Solver->solve() at phar:///usr/local/bin/composer/src/Composer/Installer.php:472
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:223
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:158
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:54
 require() at /usr/local/bin/composer:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by araviaravi** [comment]
I am sorry to say this. The solution is not working for me. I am newbie. Could you please explain in details?

**Comment by araviaravi** [comment]
I hope this should be write solution. 

I have updated composer.json as 

   "require": {
        "php": ">=7",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
        "yiisoft/yii2-imagine": "*",
	"almasaeed2010/adminlte":">=2",
	"dmstr/yii2-adminlte-asset":">=2"
    },
   "config": {
        "process-timeout": 1800,
     	"fxp-asset": {
                "repositories": {
                    "bower-asset/eve": {
                        "type": "bower-vcs",
                        "url": "https://github.com/adobe-webplatform/eve.git"
                    }
                }
            }
    },

**Comment by schmunk42** [comment]
@araviaravi See https://github.com/dmstr/yii2-adminlte-asset#faq

**Comment by schmunk42** [comment]
Please see https://github.com/dmstr/yii2-adminlte-asset/issues/133#issuecomment-337179853

**Comment by tamersolieman** [comment]
@araviaravi Thanks the issue was resolved when I add

  "config": {
    "process-timeout": 1800,
      "fxp-asset": {
        "repositories": {
          "bower-asset/eve": {
          "type": "bower-vcs",
          "url": "https://github.com/adobe-webplatform/eve.git"
          }
        }
      }
  },

**Comment by bitsnaps** [comment]
I had the same issue, it was OpenSSL version, I had to upgrade it using the following procedure:
https://www.apachefriends.org/blog/heartbleed-bug.html

**Comment by arungangula** [comment]
I am facing the similar issue. Tried every possible thing mentioned above.
Here is my composer.json require 

```
"require": {
        "php": "~7.0.0",
        "yiisoft/yii2": "2.0.*",
        "yiisoft/yii2-bootstrap": "2.0.5",
        "yiisoft/yii2-swiftmailer": "2.0.4",
        "almasaeed2010/adminlte": "2.3.2",
        "FortAwesome/Font-Awesome": "4.3.0",
        "kartik-v/yii2-widget-sidenav": "1.0.0",
        "kartik-v/yii2-export": "1.2.4",
        "mdmsoft/yii2-admin": "1.0.5",
        "dmstr/yii2-adminlte-asset": "2.2.4",
        "2amigos/yii2-ckeditor-widget": "1.0.4",
        "aws/aws-sdk-php": "3.15.2",
        "bower-asset/cropper": "2.2.5",
        "eonasdan/bootstrap-datetimepicker": "4.17.47",
        "select2/select2": "4.0.1",
        "bower-asset/magnific-popup": "1.0.0",
        "guzzlehttp/guzzle": "~6.0",
        "phpoffice/phpexcel": "^1.8",
        "bower-asset/sweetalert": "1.1.1",
        "bower-asset/TableDnD": "0.9.1",
        "bower-asset/tooltipster": "3.3.0",
        "yiisoft/yii2-redis": "*",
        "kajol22/yii2-resque": "*",
        "phpseclib/phpseclib": "^2.0",
        "google/apiclient": "^2.0",
        "googleads/googleads-php-lib": "^32.0"
    }
```

and here is the error i get

```
[Composer\Repository\InvalidRepositoryException]
  No valid bower.json was found in any branch or tag of https://github.com/jquery/jquery-dist.git,
   could not load a package from it.
```

**Comment by schmunk42** [comment]
@arungangula Related? https://chrislee.kr/wp/2018/11/11/yii2-errors-failed-to-clone-the-git-and-extra-asset-installer-paths-option-is-deprecated/

**Comment by predatorlg** [comment]
> @araviaravi Thanks the issue was resolved when I add
> 
> ```
>   "config": {
>     "process-timeout": 1800,
>       "fxp-asset": {
>         "repositories": {
>           "bower-asset/eve": {
>           "type": "bower-vcs",
>           "url": "https://github.com/adobe-webplatform/eve.git"
>           }
>         }
>       }
>   },
> ```

Thanks. The issue was resolved when I add
