### ISSUE TITLE
Update to AdminLTE 2.4

### ISSUE THREAD

**Issue by dwiprawira1989** [dmstr/yii2-adminlte-asset#125]
Can you please update the almasaeed2010/AdminLTE to version 2.4 instead of 2.0?

**Comment by schmunk42** [comment]
We're using AdminLTE from 2.0 on, depending on your project stability you currently get 2.3.11 (stable) or 2.4 (rc).

https://semver.mwl.be/#?package=almasaeed2010%2Fadminlte&version=~2.0&minimum-stability=stable

**Comment by cronfy** [comment]
There is upgrade guide for HTML in AdminLTE 2.4: https://adminlte.io/docs/2.4/upgrade-guide

Is the HTML in views changed appopriately?
