### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by vityapro** [dmstr/yii2-adminlte-asset#126]
Please update composer package, by adding crud template
`@vendor/dmstr/yii2-adminlte-asset/gii/templates/crud/simple`

**Comment by schmunk42** [comment]
Where exactly should this be added in your opinion?

**Comment by vityapro** [comment]
First of all i am sorry that don`t described that problem.
So, when i install `dmstr/yii2-adminlte-asset` package from composer i couldn't find folder with `gii/templates`, and on my opinion it some error.
Thank you for fast reply.

**Comment by schmunk42** [comment]
Which version did you get installed, it should be included in `2.4.3`

**Comment by vityapro** [comment]
Thank, now i know that problem in version, because i have `2.4.2` version installed.
