### ISSUE TITLE
No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.

### ISSUE THREAD

**Issue by yamalweb** [dmstr/yii2-adminlte-asset#128]
I'm trying to install
php composer.phar require dmstr/yii2-adminlte-asset "2.*"

./composer.json has been updated
Loading composer repositories with package information                                                                                     Updating dependencies (including require-dev)         Your GitHub credentials are required to fetch private repository metadata (https://github.com/DmitryBaranovskiy/eve.git)
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+webfoms+2017-09-20+0933
to retrieve a token. It will be stored in "/home/vagrant/.config/composer/auth.json" for future use by Composer.
Token (hidden): 
Token stored successfully.

```
Installation failed, reverting ./composer.json to its original content.

                                                                                                                                         
  [Composer\Repository\InvalidRepositoryException]                                                                                       
  No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.  
```

**Comment by schmunk42** [comment]
You're missing an auth token for GitHub, please also update your composer binary.

Duplicates:
- https://github.com/dmstr/yii2-adminlte-asset/issues/119
- https://github.com/dmstr/yii2-adminlte-asset/issues/118

**Comment by schmunk42** [comment]
Please see https://github.com/dmstr/yii2-adminlte-asset/issues/133#issuecomment-337179853

**Comment by tamersolieman** [comment]
The issue resolved when I add this section to composer.json file

`  "config": {
    "process-timeout": 1800,
      "fxp-asset": {
        "repositories": {
          "bower-asset/eve": {
          "type": "bower-vcs",
          "url": "https://github.com/adobe-webplatform/eve.git"
          }
        }
      }
  },`

**Comment by schmunk42** [comment]
@tamersolieman Thank you, this is the best solution, I think! I added that to the FAQ section.
