### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by alpiiscky** [dmstr/yii2-adminlte-asset#131]
During installing 2v

[Composer\Repository\InvalidRepositoryException]                             
  No valid bower.json was found in any branch or tag of https://github.com/Dm  
  itryBaranovskiy/eve.git, could not load a package from it.

**Comment by schmunk42** [comment]
Please search the issues first, it's the fourth time we're receiving this error.

**Comment by schmunk42** [comment]
Please see https://github.com/dmstr/yii2-adminlte-asset/issues/133#issuecomment-337179853
