### ISSUE TITLE
after updated almasaeed2010/adminlte to 2.4 package have an issue

### ISSUE THREAD

**Issue by lk-yuriy** [dmstr/yii2-adminlte-asset#132]
after update to new version can not load /js/app.min.js
We fixed dmstr/yii2-adminlte-asset version to 2.3.3 but

**Comment by schmunk42** [comment]
Please use either 
- 2.4.4 which will give you AdminLTE <2.4.0 or 
- 2.5.0-rc1 which will give you AdminLTE 2.4.0 currently.

We can not change constraints of older versions.
