### ISSUE TITLE
Cannot install package due to last commit

### ISSUE THREAD

**Issue by za4me** [dmstr/yii2-adminlte-asset#133]
[https://github.com/dmstr/yii2-adminlte-asset/commit/2dd0e2b38bf57b76fdcf65c5363a1fafe8e0bc7c](url) Hello. I think this commit breaks install package because `almasaeed2010/adminlte` dependencies cannot find `DmitryBaranovskiy/eve.git` repository.

![](http://dl3.joxi.net/drive/2017/09/25/0017/0874/1139562/62/a1ab100d1b.png)

**Comment by schmunk42** [comment]
I've create an FAQ section due to this "issue" https://github.com/dmstr/yii2-adminlte-asset/blob/master/README.md#faq

**Comment by locsob** [comment]
I have update fxpio to 1.4.1 and composer self-update 1.5.2., but still https://github.com/Dm
  itryBaranovskiy/eve.git, could not load a package from it.

**Comment by schmunk42** [comment]
Sorry, I can't tell why this is happening over an over. 
Please clear composer caches and/or vendor and try again.

**Comment by locsob** [comment]
I done it, but still error.

2017-10-16 16:12 GMT+03:00 Tobias Munk <notifications@github.com>:

**Comment by schmunk42** [comment]
Can you post a `composer.json` with which this is happening?

**Comment by locsob** [comment]
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=7.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "la-haute-societe/yii2-save-relations-behavior": "*",
        "yiisoft/yii2-authclient": "^2.1",
        "kartik-v/yii2-widget-datepicker": "@dev",
        "kartik-v/yii2-widgets": "*",
        "kartik-v/yii2-field-range": "*",
        "paulzi/yii2-nested-sets": "^1.0",
        "2amigos/yii2-ckeditor-widget": "^2.1",
        "yii-dream-team/yii2-bower.jsonupload-behavior": "*",
        "bower-asset/font-awesome": "^4.7",
        "bower-asset/swiper": "^3.4",
        "bower-asset/magnific-popup": "^1.1",
        "elasticsearch/elasticsearch": "^5.3",
        "yii-cms/yii2-robokassa": "^1.1",
        "PHPOffice/PHPExcel": "^1.8",
        "filsh/yii2-oauth2-server": "*",
        "dmstr/yii2-adminlte-asset": ">=2"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
    "config": {
        "process-timeout": 1800
    }
}


2017-10-17 11:43 GMT+03:00 Tobias Munk <notifications@github.com>:

**Comment by schmunk42** [comment]
Found the culprit :) Thanks for sharing the `composer.json`

    "dmstr/yii2-adminlte-asset": ">2"

Simply remove the `=` there's an issue with `2.0` which requires `bower-asset/adminlte`, which requires "eve".

**Comment by litvinovandrew** [comment]
The same error for the "dmstr/yii2-adminlte-asset": "1.1.1"  : 
 [Composer\Repository\InvalidRepositoryException]                                                                                       
No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.

**Comment by leroyakg** [comment]
as @litvinovandrew said, I also get same error with version 1

**Comment by schmunk42** [comment]
Hmm, we do not really support 1.x since a while.

I hesitate to do a 1.2 release which switches to "AdminLTE" via composer or npm; it might break other things.
I'd suggest the following:
- create a fork
- add it to repositories in your project's `composer.json`
- change the `composer.json` of the fork to use composer or npm
- adjust the `AssetBundle` paths in the fork
- update
- report if this fixes your issue

**Comment by schmunk42** [comment]
You can also try this workaround: https://github.com/dmstr/yii2-adminlte-asset/issues/123#issuecomment-361895567
