### ISSUE TITLE
Menu can't toggle

### ISSUE THREAD

**Issue by mazurva** [dmstr/yii2-adminlte-asset#136]
After `composer update` menu can't toggle.

**Comment by schmunk42** [comment]
Possibly related to #134 and #135 - which version of `dmstr/yii2-adminlte-asset` and `almasaeed2010/adminlte` do you have (`composer show`)?

**Comment by mazurva** [comment]
almasaeed2010/adminlte              v2.4.0
dmstr/yii2-adminlte-asset           2.5.0-rc1

**Comment by rosancoderian** [comment]
i have the same problem
almasaeed2010/adminlte v2.4.0
dmstr/yii2-adminlte-asset 2.4.3

**Comment by philippfrenzel** [comment]
the template has changed, pls. see documentation on lteadmin.io then you'll see the new needed class and the data attribute

**Comment by EndErr** [comment]
so if the template was changed why it is not updated in yii2-adminlte-asset?

**Comment by schmunk42** [comment]
fixed in 2.5.0

**Comment by alexdran** [comment]
if you still have problem I have fixed by adding data-widget variable to widget

`
        <?= dmstr\widgets\Menu::widget(
            [
                'options' => [
                    'class' => 'sidebar-menu',
                    'data-widget' => 'tree',
                ],
                'items' => $items,
            ]
        ) ?>
`
