### ISSUE TITLE
Nested items don't work.

### ISSUE THREAD

**Issue by mepoohsta** [dmstr/yii2-adminlte-asset#137]
![image](https://user-images.githubusercontent.com/9480365/31278640-6acc7390-aaae-11e7-8b41-59caea5a588a.png)

**Comment by drsdre** [comment]
This occurs with AdminLTE v 2.4.0 and up. From https://adminlte.io/docs/2.4/upgrade-guide notes:

> 
> Add .treeview to all li elements that contain sub menus in the sidebar menu. Example:
> ```
> <li class="treeview">
>   <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
>     <span class="pull-right-container">
>        <i class="fa fa-angle-left pull-right"></i>
>     </span>
>   </a>
>   <ul class="treeview-menu">
>     <li><a href="#">Link in level 2</a></li>
>     <li><a href="#">Link in level 2</a></li>
>   </ul>
> </li>
> 
> ```

**Comment by drsdre** [comment]
Fixed in pull request #138

**Comment by schmunk42** [comment]
fixed in #134 - thank you
