### ISSUE TITLE
2.5.0 backward comatibility

### ISSUE THREAD

**Issue by indeveler** [dmstr/yii2-adminlte-asset#139]
- morris.js path change (`plugins/morris` => `bower_components/morris.js`) broken filepathes in custom AdminLTE asset

- toggle menu doesn't work anymore

**Comment by indeveler** [comment]
When I change composer.json string from 
`"dmstr/yii2-adminlte-asset": "2.*"`
to 
`"dmstr/yii2-adminlte-asset": "2.4.4"`
and do `composer update` it works.

**Comment by kiruanoyuan** [comment]
Ya, same issue happened here, after "composer update".
Downgrade to "dmstr/yii2-adminlte-asset": "2.4.4"
Fixing the problem.

Thanks bro

**Comment by schmunk42** [comment]
Double check your custom code against, there were some updates in AdminLTE:

- https://adminlte.io/docs/2.4/upgrade-guide
- https://github.com/dmstr/yii2-adminlte-asset#compatibility-matrix
- https://github.com/dmstr/yii2-adminlte-asset/compare/2.5.0-rc1...2.5.0

**Comment by letsjump** [comment]
Toggle menu doesn't work because its click assign the wrong class: 
`<li class="active treeview open">`
instead of
`<li class="active treeview menu-open">`

Also the default webfont "source sans pro" isn't included anymore in AdminLTE.css and has to be included somewhere else (for example in the AdminLteAsset class)

**Comment by schmunk42** [comment]
Should be explained in https://github.com/dmstr/yii2-adminlte-asset#faq - let me know if there are other issues

**Comment by letsjump** [comment]
I also get the dropdown problem after the update to 2.5.
After the update, it is impossible to invoke a dropdown event by [[show/hide/...].bs.dropdown javascript function](https://getbootstrap.com/docs/3.3/javascript/#dropdowns-events).
As a workaround I needed to add an "onclick" attribute calling a js function:

```php
ButtonDropdown::widget([
    'label'       => 'label',
    'options'     => [
        'class'     => 'btn-sm btn-default',
        'onclick'   => 'fn:myWorkaroundJsFunction(button-id)',
        'id'        => 'btn-' . $product->id ,
    ],
    'encodeLabel' => false,
    'dropdown'    => [
        'options' => ['class' => 'imei-list-' . $product->id],
        'items'   => []
    ]
]);
```

**Comment by pptyasar** [comment]
I am using version 1 them what to do?

**Comment by schmunk42** [comment]
Check From v1.x to v2.x https://adminlte.io/docs/2.4/upgrade-guide
