### ISSUE TITLE
double vertical scrollbar

### ISSUE THREAD

**Issue by bobonov** [dmstr/yii2-adminlte-asset#14]
I use yii2 basic application and adminlte theme.
As soon as the page became longer a double vertical scroolbar appear.
One is from the windows container (which is correct), but another seem from the body container.
The one from the body prevent you to use the mouse wheel to scroll efficiently.
In plus when the body scroll the header get detached from the left menu.
I think is some problem with the javascrpt assets.

**Comment by schmunk42** [comment]
Does the original AdminLTE demo work fine for you?

**Comment by bobonov** [comment]
Yes the one which is published in the assets (demo with all widget and so on) works correctly, but this one uses cdn for bootstrap and jquery.

**Comment by schmunk42** [comment]
Could you try specifying the same jquery and bootstrap version like defined in CDN in `composer.json`, `composer update` and delete all published assets and republish.

Does this makes a difference?

**Comment by schmunk42** [comment]
May this is related to https://github.com/dmstr/yii2-adminlte-asset/pull/15

@bobonov Could you provide the versions from the CDN?

**Comment by githubjeka** [comment]
https://github.com/almasaeed2010/AdminLTE/issues/227

**Comment by son2xp2go** [comment]
Just installed and I got the same problem. How to solve this double scroll bar issue??

**Comment by githubjeka** [comment]
Change to AdminLTE 2.0

**Comment by son2xp2go** [comment]
inside my yii2-adminlte-asset folder are: 
example-views(folder)
web(folder)
widgets(folder)
composer.json
readme.md
Please help me how do i exactly do the changes?

**Comment by githubjeka** [comment]
https://github.com/dmstr/yii2-adminlte-asset/pull/29

**Comment by schmunk42** [comment]
As mentioned from @githubjeka please upgrade to version 2 - I just released the beta.

**Comment by gbstarmark** [comment]
HI,
I have tried everything on composer, but get the message can't find a stable version. "dmstr/yii2-adminlte-asset": "2.*" ? I have changed the version to everything including @dev. Nothing works any advice please?

**Comment by schmunk42** [comment]
Make sure that you have installed the latest composer and fxp/composer-asstet-plugin version.

If the error persist, please open a new issue with the full error response.
