### ISSUE TITLE
AdminLTE webfont inclusion (update documentation needed)

### ISSUE THREAD

**Issue by letsjump** [dmstr/yii2-adminlte-asset#140]
It seems that AdminLTE _2.4 update_ [moved the google web-font inclusion](https://github.com/almasaeed2010/AdminLTE/commit/235481d1d6324c1d4257f86c621700aa7f4a0b7f#diff-1f72e183078c883b0310969230ceea84) from adminlte.js to the `<head>` tag of its example pages.
Can you mention this in your documentation?
Thanks

**Comment by schmunk42** [comment]
Will update the docs, if I've found a nice way how to inlcude them. In the meantime see also https://github.com/dmstr/yii2-backend-module/commit/f44862a60c7bf0adcd409828b7ffc11671db8ea2

**Comment by letsjump** [comment]
I think that @almasaeed2010 moved the inclusion so anyone can choose which web-font to use. 
So maybe is better to recommend an inclusion in `@views/layouts/main.php`  or in an *Asset* extension of AdminLtePluginAsset class.
