### ISSUE TITLE
how to use the crud generator in yii 2 advanced

### ISSUE THREAD

**Issue by Bagrationi95** [dmstr/yii2-adminlte-asset#143]
![image](https://user-images.githubusercontent.com/23195046/31843118-4d6614b4-b602-11e7-9bd6-849534366f2d.png)

file backend/config/main-local.php
```
if (!YII_ENV_TEST) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
    ];
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        'generators' => [ //here
            'crud' => [
                'class' => 'yii\gii\generators\crud\Generator',
                'templates' => [
                    'adminlte' => '@vendor/dmstr/yii2-adminlte-asset/gii/templates/crud/simple',
                ]
            ]
        ],
    ];
}
return $config;
```
Sorry... I do not speak English =)

**Comment by githubjeka** [comment]
Whats problem? By your screenshot it's OK

**Comment by Bagrationi95** [comment]
how to use a template for gii generator?

**Comment by pa3py6aka** [comment]
You must select adminlte template in CRUD generator. I think you don't do it.
![screenshot at 25 16-45-40](https://user-images.githubusercontent.com/12895355/32002102-4eb70ada-b9a4-11e7-948f-5d5cda2f4e98.png)

**Comment by Bagrationi95** [comment]
Yes you are right, I don't do it.. Thank you =)
