### ISSUE TITLE
How to use ckeditor plugin?

### ISSUE THREAD

**Issue by syaifulrmdhn** [dmstr/yii2-adminlte-asset#145]
i can't use ckeditor in my yii2-basic

**Comment by schmunk42** [comment]
I'd recommend to use a Yii2 widget like this: https://github.com/dmstr/yii2-prototype-module/blob/master/composer.json#L20

Example usage in another module: https://github.com/dmstr/yii2-prototype-module/blob/master/src/views/html/_form.php#L43
