### ISSUE TITLE
Add support labels to Menu widget

### ISSUE THREAD

**Issue by webdevsega** [dmstr/yii2-adminlte-asset#148]
Now it's impossible to add labels to the menu items

**Comment by schmunk42** [comment]
Can you provide some example markup?

**Comment by webdevsega** [comment]
@schmunk42, you can see an example of use on the official site in menu item "Mailbox": https://adminlte.io/themes/AdminLTE/index2.html

**Comment by githubjeka** [comment]
https://github.com/dmstr/yii2-adminlte-asset#left-sidebar-menu---widget-menu
