### ISSUE TITLE
app.min.js is missing

### ISSUE THREAD

**Issue by shqear93** [dmstr/yii2-adminlte-asset#149]
Hi dmstr,
I figured that since the new version of [almasaeed2010/AdminLTE](https://github.com/almasaeed2010/AdminLTE/tree/v2.3.11/dist/js) v2.4.0 has been released he removed the file **app.min.js**, this causes a problem in your AssetBoundle bcz it's referencing to that file.

I don't know why he did this and whatever it's wrong to remove it or what, but I set my composer to use exactly the version **"=2.3.11"** the adminlte dependency, and that resolve my problem

**Comment by dyzajash** [comment]
Upgrade guide: https://adminlte.io/docs/2.4/upgrade-guide

Menu fix is second paragraph.

**Comment by runmanz** [comment]
I had this question too，when I updated the version a month ago

**Comment by stasionok** [comment]
After update to 2.5.0 theme broke like it do in previous versions. But now i can't fix that by copying app.min.js because it do not require it.
But looks like app.min.js is missing.
Rollback to 2.4.3 and manual copying add.min.js in asset folder fix trouble.

**Comment by schmunk42** [comment]
There's not much we can do about this. 

You need to stay on older versions of this extension or update your code accordingly to the upgrade guide referenced in https://github.com/almasaeed2010/AdminLTE/issues/1723

**Comment by dvilchansky** [comment]
This was a temporary fix for me, hope this will work for you too.
Now you can use this class instead of the original
Sorry for the indentation :D

`namespace different\from\original`

`class AdminLteAsset extends \dmstr\web\AdminLteAsset`
`{`
 `       public $js = [`
`            'js/adminlte.js'`
 `       ];`
`}`
