### ISSUE TITLE
zelenin/yii2-recaptcha-widget is abandoned

### ISSUE THREAD

**Issue by farmani-eigital** [dmstr/yii2-adminlte-asset#151]
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 98 installs, 0 updates, 0 removals                           
  - Installing zelenin/yii2-recaptcha-widget (0.0.1): Downloading (failed)    Failed to download zelenin/yii2-recaptcha-widget from dist: The "https://api.github.com/repos/zelenin/yii2-recaptcha-widget/zipball/2501eaf8b77229b3fae920e1bc2b630cd1c6843d" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing zelenin/yii2-recaptcha-widget (0.0.1): Cloning 2501eaf8b7

                                                                                     
  [RuntimeException]                                                                 
  Failed to clone https://github.com/zelenin/yii2-recaptcha-widget.git via https, s  
  sh protocols, aborting.                                                            
  - https://github.com/zelenin/yii2-recaptcha-widget.git                             
    Cloning into '/home/ramin/www/ninjacto.com/vendor/zelenin/yii2-recaptcha-widget  
  '...                                                                               
    remote: Invalid username or password.                                            
    fatal: Authentication failed for 'https://github.com/zelenin/yii2-recaptcha-wid  
  get.git/'                                                                          
  - git@github.com:zelenin/yii2-recaptcha-widget.git                                 
    Cloning into '/home/ramin/www/ninjacto.com/vendor/zelenin/yii2-recaptcha-widget  
  '...                                                                               
    ERROR: Repository not found.                                                     
    fatal: Could not read from remote repository.                                    
                                                                                     
    Please make sure you have the correct access rights                              
    and the repository exists.

**Comment by schmunk42** [comment]
`zelenin/yii2-recaptcha-widget` is not a dependeny of `yii2-adminlte-asset`.

Use `composer why -r zelenin/yii2-recaptcha-widget` to see where it is coming from.
