### ISSUE TITLE
add new skin color

### ISSUE THREAD

**Issue by kurniawantaari** [dmstr/yii2-adminlte-asset#152]
Is it possible to add new theme skin in local project? I want to add teal color but it seems something is missing. What I've tried 
1. create skin-teal.less and skin-teal-light.less file
2. add
 `@import "skin-teal.less";
@import "skin-teal-light.less";`
to the _all-skins.less.
3. compile those file to css and add them in dist/css folder

Any help would be appreciate

**Comment by githubjeka** [comment]
3 wrong

should be: compile main.css and add it in `@webroot/css/` folder
4. in main AppAsset class change css:

```php
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public function init()
    {
        $this->css = [
            'css/main.css',
           // ....
        ]; 
    }

    // ....
}
```

**Comment by kurniawantaari** [comment]
thanks. I'll try it.

**Comment by schmunk42** [comment]
Customization can be done in various ways. PRs with documentation about that are welcome.

Closing since it's not an issue with `yii2-adminlte-asset`.
