### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by kidzen** [dmstr/yii2-adminlte-asset#153]
i got this issue..the left menu doesnt scroll..

**Comment by schmunk42** [comment]
I don't think this is the scope of this extension, since we're just including the code from AdminLTE. 

Is there an issue in AdminLTE about that?

**Comment by kidzen** [comment]
after some googling i found [this](https://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responsive)..

and i notice that that the [demo](https://adminlte.io/themes/AdminLTE/pages/layout/fixed.html) from adminlte demo page also trigger the same warning but left menu working fine.

so, i guess my left menu problem was not related to this one..

as i stated, even with fresh install of the theme, i still cant get the left menu scrollable.

**Comment by schmunk42** [comment]
I tried the demo on my iPhone, but I found it very hard to use. While I agree that it would be nice to have separate scrolling for the menu, the current implementation does immediately stop scrolling after you lift your finger (touchend), while the standard way is that the scroll decelerates smoothly.
