### ISSUE TITLE
Menu widget fails to detect active menu item

### ISSUE THREAD

**Issue by krissss** [dmstr/yii2-adminlte-asset#158]
like #113 , still exist.

```php
$items = [
   [
        'label' => 'parent', 'icon' => 'list', 'url' => '#',
        'items' => [
            ['label' => 'sub1', 'icon' => 'circle-o', 'url' => ['/category']],
        ]
    ],
]
```

I have `'url'=> ['/category']`, `isItemActive` detect `/category` but not `/category/create` or `/category/update`.

There is no custom routing rules for this controller in urlManager configuration, And no module.

#108 fixed isItemActive in nested modules, but cause this bug. It make active only applied at index(default action), it is not applied at other action in Controller.

**Comment by schmunk42** [comment]
So you have an item with route `/category` and want it to be selected when you are on `/category/someaction` - right?

I think we'd need an additional param to enable this.

@githubjeka Any thoughts about this?

**Comment by krissss** [comment]
Yes, and that's the logic of your previous version. But after #108, its changed

**Comment by vilkh3m** [comment]
what is status of this issue ? i really need this in my current project. Must do back to previous version ?

**Comment by githubjeka** [comment]
If you need this behavior use `active` param as Closure in the one of `items` for menu

**Comment by vilkh3m** [comment]
@githubjeka can you please give some example ?
i try many way but no success :(

My menu:
- Adm 
- - Admin
- - - User [/user/index]
- - - Menu [/admin/menu/index]
....
- - ....
When i go /user/index User is active and thats ok but when i go to /user/view?id=1 all menu is collapse :(

**Comment by githubjeka** [comment]
Like this https://github.com/yiisoft/yii2/issues/12869#issuecomment-258843920

**Comment by vilkh3m** [comment]
i use yii2-admin so my menu is generated from mysql looks i must modify yii2-admin menu table to add new field active :/ not clean solution but thx for answer

**Comment by vilkh3m** [comment]
I make it works :)
This is how i do this:
left.php:
```php
$callback = function ( $menu ) {
    $data = eval($menu[ 'data' ]);
    return [
        'label' => $menu[ 'name' ],
        'url'   => [ $menu[ 'route' ] ],
        'icon'  => (isset($data['icon']) ? $data['icon'] : ''),
        'items' => $menu[ 'children' ],
        'active' => (isset($data['activeOnRoutes']) ? in_array(Yii::$app->controller->getRoute(), $data['activeOnRoutes']) : null )
    ];
}

dmstr\widgets\Menu::widget(
[
    'options' => [ 'class' => 'sidebar-menu tree', 'data-widget' => 'tree' ],
    'items'   => MenuHelper::getAssignedMenu( Yii::$app->user->id, null, $callback ),
];
```
And in yii2-admin menu table field "data" looks like this:
example of Role position in menu:
```php
return ['icon'=>'cog','activeOnRoutes'=>['admin/role/index','admin/role/view','admin/role/update','admin/role/create']];
```

This way i can set icon for position in menu and when need this position to be active
thx for help :)
