### ISSUE TITLE
An error occurred after the update of the yii2 version

### ISSUE THREAD

**Issue by Mr-sunK** [dmstr/yii2-adminlte-asset#161]
An error occurred after the update of the yii2 version
![_20180327181805](https://user-images.githubusercontent.com/33918985/37961561-3af349b8-31eb-11e8-9966-1151e21e619e.jpg)

**Comment by schmunk42** [comment]
Could you try `composer require "bower-asset/jquery:2.*"` to see if this would fix your problem.

Looks not directly related to `adminlte` on first sight, since the error comes from `jquery-ui`.
