### ISSUE TITLE
Sidebar cannot scrolling in fixed body (only content can scrolled)

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [dmstr/yii2-adminlte-asset#164]
Dear dmst,

I use this yii2 admin-lte version : "dmstr/yii2-adminlte-asset": "2.4.4",
Sidebar scrolled not working when body:
`<body class="hold-transition <?= \dmstr\helpers\AdminLteHelper::skinClass() ?> sidebar-mini fixed ">`

**Comment by schmunk42** [comment]
Please read https://github.com/dmstr/yii2-adminlte-asset#upgrading and upgrade. Also devices, browsers, on which this occurs would be a helpful information.
