### ISSUE TITLE
A security issue.

### ISSUE THREAD

**Issue by 112Legion112** [dmstr/yii2-adminlte-asset#165]
If a user is a guest.
And a user will try to go to the not existing controller or action user will get all admin actions. 

![image](https://user-images.githubusercontent.com/20613430/40045590-2849d802-5844-11e8-8111-f54e91baeb8c.png)

To fix this, you can add to the top of view **error** the following code:
```
if (Yii::$app->user->isGuest) {
    $this->context->layout = 'main-login';
}
```

**Comment by schmunk42** [comment]
How is this related to this **asset-bundle**?

**Comment by 112Legion112** [comment]
I got that problem once and wanted to share that.
I think if in default, not login user cannot see the admin layout it will be good.

**Comment by schmunk42** [comment]
Which files of this extension are you using?
Did you read https://github.com/dmstr/yii2-adminlte-asset#quick-start?

**Comment by 112Legion112** [comment]
I had read all documentation. 
I am using  Advanced Application Template.
I extracted those files to the folder "frontend/views/" [according to documentation](https://github.com/dmstr/yii2-adminlte-asset#customization).

**Comment by schmunk42** [comment]
Logic *should* not be put into views, I think your problem is specific to your application setup.
The layout and views we provide are just examples, which need to be adjusted to your needs.

I don't think we can do much about it.
