### ISSUE TITLE
treeview menu-open by default

### ISSUE THREAD

**Issue by deshario** [dmstr/yii2-adminlte-asset#167]
How to open treeview menu-open by default ...  like in the image below .. is there way to do it in yii2..

![dropdown](https://user-images.githubusercontent.com/11426727/41736186-fc0f3a0e-75b5-11e8-8d36-148cc6348814.PNG)

     $menuItems = [
                      [
                            'label' => 'Tools',
                            'icon' => 'cog',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Verifications', 'icon' => 'qrcode', 'url' => ['donation-verified/index'],],
                                ['label' => 'Profile', 'icon' => 'user-o', 'url' => ['user/profile'] ],
                                ['label' => 'Decryption', 'icon' => 'user-o', 'url' => ['user/hashing'] ],
                                ['label' => 'Logout', 'url' => ['site/logout'], 'template' => '<a href="{url}" data-method="post"><i class="fa fa-sign-out"></i>{label}</a>'],
                            ],
                        ]
                ];

> echo dmstr\widgets\Menu::widget([
            'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
            'items' => $menuItems
        ]);

**Comment by schmunk42** [comment]
You need to set the `active` key of an item.

See also https://github.com/dmstr/yii2-adminlte-asset/blob/master/widgets/Menu.php

**Comment by deshario** [comment]
I tried to set class active but its not working ... do u have examples to make it clear. Thankx

**Comment by schmunk42** [comment]
```
[
  'active' => true, 
  'label' => 'Verifications', 
  'icon' => 'qrcode', 
  'url' => ['donation-verified/index'],
],
```
