### ISSUE TITLE
Make crud generator based on GIIANT

### ISSUE THREAD

**Issue by mohdqasim98** [dmstr/yii2-adminlte-asset#175]
Is it possible to use the crud generator based on GIIANT (https://github.com/schmunk42/yii2-giiant) instead of default GII.
I always used GIIANT in my YII2 projects, since its a bit advance.So is it possible to configure the functionality of GIIANT and you your crud generator together ?

**Comment by schmunk42** [comment]
Nice to hear that :)

We're using this asset-bundle with the default CRUD templates from Giiant, usually we use a box layout for the CRUDs so they have a white background.

It's not required to use the CRUD templates from this repo.

Please let me know if you have additional questions.
