### ISSUE TITLE
rmrevin/yii2-fontawesome conflicts

### ISSUE THREAD

**Issue by coderovich** [dmstr/yii2-adminlte-asset#176]
Hello.
I can't install "rmrevin/yii2-fontawesome": "~3.2" using composer because your package depends on "rmrevin/yii2-fontawesome": "~2.9".  What's the point? As I understand, your project does not require "fontawesome"... Or may be you can increase the minimal required version in your composer file?

![clip2net_180919103157](https://user-images.githubusercontent.com/11044347/45737777-67f18d80-bbf7-11e8-9833-fbfea7ed9a03.png)

**Comment by schmunk42** [comment]
You'd need https://github.com/dmstr/yii2-adminlte-asset/releases/tag/3.0.0-alpha1 - it has no constraint.

**Comment by coderovich** [comment]
thanx!
