### ISSUE TITLE
Arrow left side bar menu faulty

### ISSUE THREAD

**Issue by eothein** [dmstr/yii2-adminlte-asset#179]
After the last update, the arrows in the left side bar appear to do some strange things. 

What can I do to solve this?

<img width="220" alt="schermafbeelding 2018-10-19 om 17 35 56" src="https://user-images.githubusercontent.com/7603307/47228495-a8deec80-d3c5-11e8-890a-b74783616e27.png">

**Comment by schmunk42** [comment]
Which version of this extension are you using?
Might be related to missing/wrong CSS classes...

**Comment by eothein** [comment]
Hello @schmunk42 : I solved the issue a couple of hours ago. 
I'm also using the [Icon Library from Kartik](http://demos.krajee.com/icons) which loaded a newer version of fontawesome. These conflicted with each other.

The solution was to drop the library, and only use html to produce the Icon...

Thanks for replying
