### ISSUE TITLE
AdminLTE v.2

### ISSUE THREAD

**Issue by githubjeka** [dmstr/yii2-adminlte-asset#18]
AdminLTE v.2 has [new structure forlder](https://github.com/almasaeed2010/AdminLTE/tree/2.0.0 ).

[Demo](http://almsaeedstudio.com/themes/AdminLTE/index2.html)
Need new branch or how?

**Comment by schmunk42** [comment]
Hi Evgeniy,

thanks for pointing out the new release. 
I added a 1.0.0 tag for AdminLTE 1 and a branch alias for v2.
Would really like to hear your feedback about it. 

If we need to fix something in v1 there's a 1.0 branch.
I haven't really tried v2 out yet, but this look like to most sane way to me.

Best regards and thanks for you work.
schmunk
