### ISSUE TITLE
Update to AdminLTE 2.4.9

### ISSUE THREAD

**Issue by daniele-athome** [dmstr/yii2-adminlte-asset#186]
Just a reminder:

https://github.com/almasaeed2010/AdminLTE/releases/tag/v2.4.9

Thank you :-)

**Comment by schmunk42** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/dmstr/yii2-adminlte-asset/issues/125 (Update to AdminLTE 2.4), https://github.com/dmstr/yii2-adminlte-asset/issues/132 (after updated almasaeed2010/adminlte to 2.4 package have an issue), https://github.com/dmstr/yii2-adminlte-asset/issues/18 (AdminLTE v.2), https://github.com/dmstr/yii2-adminlte-asset/issues/118 (error installing yii2-adminlte-asset "2.*"), and https://github.com/dmstr/yii2-adminlte-asset/issues/140 (AdminLTE webfont inclusion (update documentation needed)).

**Comment by schmunk42** [comment]
We are requiring `^2.4.0`, so you should get `2.4.9` when running `composer update`.

But be aware of https://github.com/dmstr/yii2-adminlte-asset/issues/185

**Comment by daniele-athome** [comment]
> We are requiring `^2.4.0`, so you should get `2.4.9` when running `composer update`.

Sure, but I thought that probably your composer.lock should be updated as well.

> But be aware of #185

That was my laziness talking :-) I'll have a look and make a PR when I have some time.

**Comment by schmunk42** [comment]
> Sure, but I thought that probably your composer.lock should be updated as well.

That's just for testing ;) It has no effect on your project. But actually we don't run automated tests here.

**Comment by daniele-athome** [comment]
> That's just for testing ;) It has no effect on your project. But actually we don't run automated tests here.

I know, it was just a matter of keeping stuff aligned that's all.
