### ISSUE TITLE
Missing Layout Options tab?! 

### ISSUE THREAD

**Issue by jolierouge** [dmstr/yii2-adminlte-asset#187]
![1](https://user-images.githubusercontent.com/52527274/60809462-9b9ba500-a182-11e9-9e02-1537db773c47.PNG)

**Comment by schmunk42** [comment]
What are you missing? An example?

This repo just provides an asset bundle.

**Comment by jolierouge** [comment]
Tobias, I am a Yii2 beginner. My question is: In order to install yours
Yii2 AdminLTE Asset Bundle, Had I already to install AdminLTE Bootstrap
Admin Dashboard Template? If not why, when I install AdminLTE Asset Bundle,
the Layout Options Tab is "missing"?

Kind Regards,

Rogério

P.s.: Why is not loaded the app.min.js file(backend>web>assets>...>js)  by
default, giving me a browser error, compromising the normal operation of
the sidebar-toggle(on left) collapsing and gears open (on right)?


[image: image.png]

Tobias Munk <notifications@github.com> escreveu no dia segunda, 8/07/2019
à(s) 13:43:

**Comment by schmunk42** [comment]
> Had I already to install AdminLTE Bootstrap Admin Dashboard Template? 

What is this, a Yii 2 extension?

> If not why, when I install AdminLTE Asset Bundle, the Layout Options Tab is "missing"?

That depends on the layout view, I think we're just missing an example here.
I.e. I have added that here https://github.com/dmstr/yii2-backend-module/tree/master/src/views/layouts as `control-sidebar.php`

**Comment by schmunk42** [comment]
Here's an example https://github.com/dmstr/yii2-backend-module/blob/master/src/views/layouts/_control-sidebar.php - see also above.

This is not Yii 2 specific, it's "just" HTML and CSS from AdminLTE.
