### ISSUE TITLE
GET .../css/AdminLTE.min.css net::ERR_ABORTED 500

### ISSUE THREAD

**Issue by vprivaloff** [dmstr/yii2-adminlte-asset#195]
Hello! If I set the value to 'request' => ['baseUrl' => ''] in config/main.php, then the styles are not connected. The main task is to remove "backend / login" from the address bar. The administrative panel is located on the subdomain, and redirected through the symlink to the backend

this is what i get in the browser console

`GET https://admin.site.com/assets/234102c8/css/bootstrap.css net::ERR_ABORTED 500 login:12`
`GET https://admin.site.com/assets/fb27e61c/css/skins/_all-skins.min.css net::ERR_ABORTED 500 login:14`
`GET https://admin.site.com/assets/fb27e61c/css/AdminLTE.min.css net::ERR_ABORTED 500 login:13`
`GET https://admin.site.com/assets/f2d3927c/css/font-awesome.min.css net::ERR_ABORTED 500 login:11`

my .htaccess (frontend)

`Options +FollowSymLinks
IndexIgnore */*

RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule . index.php

RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_URI} !^/backend
RewriteCond %{HTTP_HOST} ^admin.site.com$ [NC]
RewriteRule ^index\.php(.*)$ /backend/$1 [L,QSA]`

**Comment by schmunk42** [comment]
This is not really related to this extension, please ask this question over here:
- https://forum.yiiframework.com/c/yii-2-0/5
or
- https://www.yiiframework.com/chat
