### ISSUE TITLE
Multilevel not working

### ISSUE THREAD

**Issue by Shokhrukh2606** [dmstr/yii2-adminlte-asset#196]
I have installed your plugin but multilevel list not opening can you help, please?

**Comment by schmunk42** [comment]
Please provide an example showing the error.

**Comment by Shokhrukh2606** [comment]
It shows any errors on console, but not opening
![image](https://user-images.githubusercontent.com/33511637/82492073-0afe5700-9aff-11ea-98da-d07be88a8361.png)
![image](https://user-images.githubusercontent.com/33511637/82492212-413bd680-9aff-11ea-9341-e040ea9027b3.png)
And array passed to menu widget:
```  
    [
        'label' => 'Same tools',
        'icon' => 'fa fa-share',
        'url' => '#',
        'options'=>['class'=>'treeview'],
        'items' => [
            [
                'label' => 'Level One',
                'icon' => 'fa fa-circle-o',
                'url' => '#',
            ],
            [
                'label' => 'Level One',
                'icon' => 'fa fa-circle-o',
                'url' => '#',
            ],
        ],
    ]

**Comment by schmunk42** [comment]
Which version do you use?

Did you try the example views?
https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/yiisoft/yii2-app/layouts/left.php#L12

**Comment by Shokhrukh2606** [comment]
I am using version ~2.3.0, I also tried example that you gave but didn't work

**Comment by Shokhrukh2606** [comment]
I tried to use as example in pages it worked properly
