### ISSUE TITLE
Class 'dmstr\adminlte\web\AdminLteAsset' not found Version 3.0.0 beta1

### ISSUE THREAD

**Issue by imbaShadow** [dmstr/yii2-adminlte-asset#197]
I downloaded the archive, and manually put everything into files in the vendor / dmstr and I get this error
And if you install through the composer everything works, but version 2.6.2 is downloaded there
And I want a third.

**Comment by schmunk42** [comment]
> And if you install through the composer everything works, but version 2.6.2 is downloaded there
And I want a third.

Specify `^3.0.0-beta1` as your version constraint.
