### ISSUE TITLE
menu's  options

### ISSUE THREAD

**Issue by xiaoyixiang** [dmstr/yii2-adminlte-asset#198]
Hello，thinks for your yii2-adminlte-asset , I am using it,My callback function is like this
```
$callback = function($menu){
    $data = Json::decode($menu['data'], true);
    return [
        'label' => $menu['name'],
        'url' => [$menu['route']],
        'options' => $data,
        'items' => $menu['children'],
    ];
};
```
 but it‘’s seem to not work, the style in HTML is class="fa fa-circle-o",and I try to debug , found that there are never used options ($data) in Menu class, so when I try to like below, 
```
$callback = function($menu){
    $data = Json::decode($menu['data'], true);
    return [
        'label' => $menu['name'],
        'url' => [$menu['route']],
        'icon' => $data['icon'],
        'visible' => $data['visible'],
        'items' => $menu['children'],
    ];
};
```
it work!
but it looks different from the README.md. Is there anything wrong with my usage? please

**Comment by githubjeka** [comment]
can not understand anything
