### ISSUE TITLE
Version 1.* not working

### ISSUE THREAD

**Issue by chabberwock** [dmstr/yii2-adminlte-asset#20]
when installing version 1.* in composer i get the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dmstr/yii2-adminlte-asset 1.0.x-dev requires bower-asset/admin-lte ~1.3 -> no matching package found.
    - dmstr/yii2-adminlte-asset 1.0.0 requires bower-asset/admin-lte ~1.3 -> no matching package found.
    - Installation request for dmstr/yii2-adminlte-asset 1.* -> satisfiable by dmstr/yii2-adminlte-asset[1.0.0, 1.0.x-dev].

Is there any way to fix this?

**Comment by schmunk42** [comment]
Global asset plugin, right? ;)
