### ISSUE TITLE
do not publish whole bower folder in asset bundle (v1)

### ISSUE THREAD

**Issue by schmunk42** [dmstr/yii2-adminlte-asset#21]
we need another solution for font-awesome

**Comment by Faryshta** [comment]
https://github.com/rmrevin/yii2-fontawesome/blob/master/AssetBundle.php how about this? we can make it a dependency

**Comment by schmunk42** [comment]
Yeah, we [have that for v2](https://github.com/dmstr/yii2-adminlte-asset/blob/master/composer.json#L22).
Another solution would be a `beforeCopy` filter for the asset-bundle.

PRs highly welcome!

**Comment by Faryshta** [comment]
Thats cool, then why not close this issue? I think the dependency solves the issue or does it cause any problem?

**Comment by schmunk42** [comment]
No, we still have to update the asset bundle in v1.

**Comment by githubjeka** [comment]
There are no movements for a long time.
