### ISSUE TITLE
Disable/Enable side menu item when a specific page is loaded

### ISSUE THREAD

**Issue by kaynewilder** [dmstr/yii2-adminlte-asset#23]
Is this possible? That I disable a side menu item, "Change Password" for example, and when a specific page is loaded, say `staff.php`, that disabled menu item will be enabled.

**Comment by schmunk42** [comment]
We'd also like to have this feature, but no implementation plans yet.

If anyone can come up with a PR, they are always highly welcome.

**Comment by githubjeka** [comment]
I don't know to need PR with `main-*.php` , where `*` is `sidebar-collapse` , `layout-boxed` and `fixed`.

@kaynewilder you can copy file `main.php` to `main-sidebar-collapse.php` and add to body `sidebar-collapse` and in controller use `$this->layout = '//main-sidebar-collapse.php'`

**Comment by Grezvany13** [comment]
@kaynewilder yii\widgets\Menu already supports this, in some way.

You can add the variable 'visible' to the Menu list to define if it should be visible (or actually available) in the rendered menu.

For example:
````
use dmstr\widgets\Menu;

        Menu::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => 'Pages',
                    'url' => ['page'],
                    'icon' => 'fa fa-file-o',
                    // you must be logged in to see and add pages in menu
                    'visible' => !(Yii::$app->user->isGuest)
                    'items' => [
                        [
                            'label' => 'View Pages',
                            'url' => [
                                'page'
                            ],
                        ],
                        [
                            'label' => 'New Page',
                            'url' => [
                                'page/add'
                            ],
                        ],
                    ],
                ],
            ],
        ]);
````
Here you can add any logic you want per menu (sub)item, which also hides all child items.

Of course you can also do it the other way; hide it by default, and only show on specific cases.

**Comment by schmunk42** [comment]
fixed by https://github.com/dmstr/yii2-adminlte-asset/pull/61
