### ISSUE TITLE
Accidently updated to v2

### ISSUE THREAD

**Issue by RamzyVirani** [dmstr/yii2-adminlte-asset#25]
I previously installed v1 with composer. and yesterday i executed composer update. now its updated to v2 and the template is messed up (screenshot below).  Can you please tell me the steps how to fix it?

![image](https://cloud.githubusercontent.com/assets/8522676/6703859/2ebf015e-cd63-11e4-8773-6dc2b0c95089.png)

**Comment by schmunk42** [comment]
Try `composer require dmstr/yii2-adminlte-asset:1.*`

**Comment by RamzyVirani** [comment]
I executed the command you suggested but did not got any success.

Digging into the files and folders, I just observed that files in "/vendor/.../dmstr/yii2-adminlte-asset" are not the main problem. the main problem I found is CSS / JS files from "/vendor/bower/admin-lte".


I am working on PHP since 4 years but never used composer. I am using composer for the first time, so please help me out. :)

**Comment by schmunk42** [comment]
Have you installed the asset plugin globally?

**Comment by RamzyVirani** [comment]
I installed Yii2 in a sub-directory of my webserver via composer.phar. (Composer is not installed on my webserver,) then I installed adminlte with below command. This was done approximately a month ago when Adminlte v2 was not even introduced.
`php composer.phar require --prefer-dist dmstr/yii2-adminlte-asset "*"`

Day before yesterday, I update command to update my packages with below command. 
`php composer.phar update`

Now my applications is a mess (screenshot shared previously).


Can you please describe "Globally"? I am new user of composer and do not know much about it

**Comment by schmunk42** [comment]
See the README https://github.com/yiisoft/yii2/tree/master/apps/advanced#install-via-composer

    php composer.phar global require "fxp/composer-asset-plugin:1.0.0"

or https://github.com/phundament/app#composer-installation

**Comment by RamzyVirani** [comment]
Yes I executed this command when installing Yii2.

**Comment by schmunk42** [comment]
Can you show your output of:

    php composer.phar show --installed
    php composer.phar global show --installed

**Comment by RamzyVirani** [comment]
Please see screenshot below.
`php composer.phar show --installed`
![image](https://cloud.githubusercontent.com/assets/8522676/6728696/61572c96-ce4d-11e4-81db-ca1d0827eef2.png)

`php composer.phar global show --installed`
![image](https://cloud.githubusercontent.com/assets/8522676/6728709/8038daf6-ce4d-11e4-8306-a517a865be38.png)

**Comment by schmunk42** [comment]
I can't spot `dmstr/yii2-adminlte-asset` and you have `beta4` instead of the stable 1.0.0 installed.
Try to add and update these packages.

**Comment by tepaleguiojo** [comment]
Why is that `yii2-adminlte-asset : 1.*` installs the adminlte v2.0.5 instead of v1.1.0.

**Comment by Quexer69** [comment]
Hi @all, that was an accidentally and unnecessary push of a tag to the wrong branch. I really have to apologize for that.

We fixed that by adding a `2.0.0-alpha1` tag to `branch master`, which is admin-lte v2.

Please check if this is working for you and I would like to hear if it´s all fine again.

Sorry for the inconvenience!

**Comment by RamzyVirani** [comment]
I fixed it by myself by applying CSS classes to my custom (copied) layout files from "http://almsaeedstudio.com/themes/AdminLTE/index2.html". Anyways, Thanks for your efforts and I really appreciate your work.
