### ISSUE TITLE
AdminLte Ver 1 - Links are brocken

### ISSUE THREAD

**Issue by matnatalis** [dmstr/yii2-adminlte-asset#26]
Thanks for the nice theme
I have tried to install version 1 but all the links are broken and and the layout is a bit messed up. 
It seems the required files are not generated in the assets folder.  I have tried to  run the command composer global require "fxp/composer-asset-plugin:1.0.0" and re-install again theme still there are brocken links.

**Comment by schmunk42** [comment]
We had some problem with our v1.1.0 - did you make sure you have v1.1.1 of yii2-adminlte-asset?

**Comment by matnatalis** [comment]
Thank you alot V1.1.1 works
