### ISSUE TITLE
adminlte2 icons not working on other browsers aside from chrome

### ISSUE THREAD

**Issue by son2xp2go** [dmstr/yii2-adminlte-asset#32]
Using google chrome, icons works perfectly by using other browsers, icons are not showing.

**Comment by schmunk42** [comment]
Could you post the URLs which are broken, eg. a screenshot of Network or Resources Inspector?

**Comment by son2xp2go** [comment]
I have posted the same question at stackoverflow (http://stackoverflow.com/questions/29761689/icons-shows-in-chrome-but-not-in-other-browsers?noredirect=1#comment47658865_29761689) and I figured out already the answer. Its just that the font was not loaded well.
