### ISSUE TITLE
Some newbie issues with AdminLTE Asset Bundle

### ISSUE THREAD

**Issue by XuriDabur** [dmstr/yii2-adminlte-asset#34]
I recently (a couple of days ago) downloaded the AdminLTE Asset Bundle for usage with Yii2 Advanced, by adding the following line to composer.json: **"dmstr/yii2-adminlte-asset": "2.*@beta"**

After it was done downloading and installing, I copied the layout files from **vendor/dmstr/yii2-adminlte-asset/example-views/yiisoft/yii2-advanced-app/layouts/** into my **frontend/views/layouts/** folder (and modified the main.php layout file to point to *frontend* instead of *backend*).

I then created a new, blank index.php view page and setup a controller action for it. 

When loading up the new page, I see the adminLte layout (with "blue skin"), but I have some issues that I have been unable to solve, and could use some assistance with.

**Issue 1:** The "left.php" layout file contains a basic menu setup through a Nav widget. When I tried to add a submenu to one of the entries in this basic menu, they were added to the page as a "dropdown" toggle, and not as an "accordion" as seen in the example/demo pages included with adminLTE. I tried manually adding classes "treeview" and "treeview-menu" to the menu entries, but that just resulted in the submenu items no longer showing up at all. Is there an example of a simple Nav widget menu setup with submenus? Here's how I tried to do it:
```php
        Nav::widget(
            [
                'encodeLabels' => false,
                'options' => ['class' => 'sidebar-menu'],
                'items' => [
                    [
                        'label' => 'Menu Header',
                        'url' => '#',
                        'options'=>['class'=>'header']
                    ],
                    ['label' => '<span class="fa fa-circle-o"></span> Menu Entry', 'url' => ['/contacts']],
                    ['label' => '<span class="fa fa-circle-o"></span> Menu Entry', 'url' => ['/projects']],
                    ['label' => '<span class="fa fa-circle-o"></span> Menu With Submenu',
                        'options' => ['class' => 'treeview'],
                        'items' => [
                            ['label' => '<span class="fa fa-file-code-o"></span> SubMenu Entry', 'linkOptions' => ['class' => 'treeview-menu'], 'url' => ['/news']],
                            ['label' => '<span class="fa fa-file-code-o"></span> SubMenu Entry', 'linkOptions' => ['class' => 'treeview-menu'], 'url' => ['/articles']],
                        ]],
                    ['label' => '<span class="fa fa-file-code-o"></span> Gii', 'url' => ['/gii']],
                    ['label' => '<span class="fa fa-dashboard"></span> Debug', 'url' => ['/debug']],
                ],
            ]
        );
```
See attached image adminlte-01.jpg to see how it looks.

**Issue 1b:** Not sure if this is related to issue 1, but when I hover over menu items that have class "header", the hover effect doesn't extend to the complete width of the sidebar menu like it does with the other menu items. See attached image adminlte-02.jpg.

**Issue 2:** The footer on my new, blank page, doesn't extend across the entire page, but leaves a gap between the footer and the collapsable sidebar on the left. If I collapse the menu, the footer extends all the way as it should, but if I toggle it back open, the footer is pushed so far to the right there would be enough space for a second sidebar inbetween it and the existing sidebar. No idea what's causing this. :/ See attached image adminlte-03.jpg

**Issue 3:** The example images (like profile image) that come with the demo-setup aren't showing up. Checked source, and they seem to point to a web/assets/ folder that doesn't exist. I tried to preview the quick example by modifying theme view path in main config, too, but the images still don't show up. All the images currently reside in the vendor/bower/admin-lte/dist/img/ folder.

I'm including some images to illustrate the problems, and hope someone can help me out :/
![adminlte-01](https://cloud.githubusercontent.com/assets/1527271/7394152/450e4f28-ee92-11e4-87d1-c83148caf2c3.jpg)
![adminlte-02](https://cloud.githubusercontent.com/assets/1527271/7394153/45106ede-ee92-11e4-9b07-a9c96fc4531b.jpg)
![adminlte-03](https://cloud.githubusercontent.com/assets/1527271/7394154/451176f8-ee92-11e4-8fd7-39eb103ead15.jpg)

**Comment by githubjeka** [comment]
Please update your code.

To solve the problem of submeny see https://github.com/dmstr/yii2-adminlte-asset/blob/c1a02115e4b60a8f920332dbd463e70df3470d1a/example-views/yiisoft/yii2-app/layouts/left.php#L52
