### ISSUE TITLE
plugins assets

### ISSUE THREAD

**Issue by Faryshta** [dmstr/yii2-adminlte-asset#36]
adminlte include several plugins and those are not included on the `dmstr\web\AdminLteAsset` asset class.

the best way to load those plugins is to make an asset for each of them, for example

```php
class ICheckAsset extends AssetBundle
{
    public $sourcePath = '@bower/admin-lte/plugins/iCheck';
    public $css = [
        'all.css'       
    ];
    public $js = [
        'icheck.min.js'
    ];
    public $depends = [
        'dmstr\web\AdminLteAsset',
    ];
}
```

**Comment by githubjeka** [comment]
Can you send Pull Request?

**Comment by githubjeka** [comment]
How do I use the `yii2-adminlte-asset`?

Copy all views to `views` folder. Copy `AlertWidget`. Copy main `css` and `js` to `@web`. 
Delete `yii2-adminlte-asset`.

If you need some plugins from `\vendor\bower\admin-lte\plugins\` , then better to connect separately through composer for avoid collisions.

Who thinks that?

**Comment by schmunk42** [comment]
What's about those?
https://github.com/Insolita/yii2-adminlte-widgets

**Comment by githubjeka** [comment]
Insolita is a good girl :)

**Comment by githubjeka** [comment]
Her widgets used only adminLte.css, not `admin-lte\plugins\`

**Comment by Faryshta** [comment]
https://github.com/Faryshta/yii2-adminlte-asset/tree/assets here is the starting work to port all the plugins to assets.

**Comment by Faryshta** [comment]
i am starting to doubt the adminlte plugins. are they plugins designed for lte? do those plugins have their own repositories?

i see jquery and jquery ui on the plugins folder. that doesn't make sense.

**Comment by Faryshta** [comment]
@almasaeed2010 hi, i would like to ask about the plugins forlder on adminlte. Are those independent projects or are they also maintained by you?

**Comment by Faryshta** [comment]
@githubjeka what do you think I should do about this issue? i am thinking to close it and add the plugin assets as composer suggestions or requirements

**Comment by githubjeka** [comment]
Plugins is better to add by Bower. And plug them into their AssetBundle.

**Comment by Faryshta** [comment]
i agree but adminlte is not doing it. i ask mostly about the assets.

For example the ICheckAsset I posted above. Should we find the assets from other projects and include them as composer dependencies?

**Comment by githubjeka** [comment]
Nope. Let those do it who need it.

**Comment by Faryshta** [comment]
Closing this issue then. I see no good way to make assets for the plugins based on the adminlte package.

**Comment by jimmyurl** [comment]
How to get started with adminlte plugins after installation in yii2

**Comment by schmunk42** [comment]
@jimmyurl Plugins are not directly supported by this extension, you can either include the JavaScripts from `almasaeed/AdminLte` or use yii2-extensions.
