### ISSUE TITLE
plugin widgets

### ISSUE THREAD

**Issue by Faryshta** [dmstr/yii2-adminlte-asset#37]
some of the admin lte assets would work very fine as yii2 widgets, for example the tree-view menu used https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/yiisoft/yii2-app/layouts/left.php#L53 would make perfect sense to turn it into nested Widgets.

**Comment by githubjeka** [comment]
Tree-view can not be realized via Nav widget Yii2, because Bootstrap doesn't support sub-dropdown menus. Need to rewrite the class.

P.S. For me html normally. Let's send PR :)

**Comment by eothein** [comment]
Could you not use the nav widget from Kartik?

**Comment by Faryshta** [comment]
@eothein which one? kartik has posibly more extensions than the yii2 core :)
