### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by Faryshta** [dmstr/yii2-adminlte-asset#38]
I am working on a PR right now and i noticed there is an issue with the namespace.

Right now the namespace for the `AdminLteAsset` class is `dmstr\web` and the PSR 2 specifies that the namespace should start with `vendor\package`

So I think we need to change it to

```php
namespace dmstr\adminlte\assets;
```

For the assets and

```php
namespace dmstr\adminlte\widgets;
```

For widgets. Specially since the `dmstr`vendor has already many packages and most of them contains assets or widgets.

**Comment by schmunk42** [comment]
We use the same namespacing as yiisoft/yii2 for the extensions released under `dmstr`, therefore not the usual package/vendor - it's rather replacing yii with dmstr.
There should be no autoloading conflicts, that's what namespaces are for.

**Comment by Faryshta** [comment]
https://github.com/dmstr/yii2-migrate-command/blob/master/composer.json

https://github.com/dmstr/yii2-app-command/blob/master/composer.json

Check the autoloading namespace. Both of this repositories will use the `dmstr\\console\\controllers\\` namespace and will load different folders.

One will load controllers from `vendor/dmstr/yii2-app-command/controllers` and the other from `vendor/dmstr/yii2-migrate-command/controller` which can cause autoloading problems depending which one executes first.

The best way to avoid it is to use the `vendor\package` structure for namespaces.

**Comment by githubjeka** [comment]
```php
// autoload_psr4.php

return array(
    'yii\\composer\\' => array($vendorDir . '/yiisoft/yii2-composer'),
    'yii\\' => array($vendorDir . '/yiisoft/yii2'),
    'mikehaertl\\shellcommand\\' => array($vendorDir . '/mikehaertl/php-shellcommand/src'),
    'dmstr\\console\\controllers\\' => array($vendorDir . '/dmstr/yii2-migrate-command', $vendorDir . '/dmstr/yii2-app-command/controllers'),
    'cebe\\markdown\\' => array($vendorDir . '/cebe/markdown'),
);

```

Use as

```php
<?php

require 'vendor/autoload.php';

new dmstr\console\controllers\MigrateController(1, 'app');
new dmstr\console\controllers\BaseAppController(2, 'app');
```


Conflict

```php
<?php
use dmstr\console\controllers;

require 'vendor/autoload.php';

new MigrateController(1, 'app');
new BaseAppController(2, 'app');
```

It is more a question for @schmunk42 because necessary to change namespace for all repositories. I am not authorized.

**Comment by schmunk42** [comment]
@Faryshta 
> One will load controllers from vendor/dmstr/yii2-app-command/controllers and the other from vendor/dmstr/yii2-migrate-command/controller which can cause autoloading problems depending which one executes first.

Certainly, we have to make sure, that we don't have the same ClassNames across repositories - but that is feasible.

@githubjeka
I'll need to double check your example code, from my `autoload_psr4.php` I'd have said this should work, although I haven't tested it so far.

    'dmstr\\console\\controllers\\' => array(
      $vendorDir . '/dmstr/yii2-migrate-command', 
      $vendorDir . '/dmstr/yii2-app-command/controllers', 
      $vendorDir . '/dmstr/yii2-yaml-converter-command'
    ),

**Comment by Faryshta** [comment]
@schmunk42 don't you think that it causes an extra troubleshooting?

First there are many classes names that are used very commonly on packages such as 'User', 'SiteController', 'BaseController', 'Module', etc.

And it does causes a psr-4 issue when autoloading as told by @githubjeka I honestly think that the path of lest resistance would be to make the version 2 of this project PSR-2 compatible.

**Comment by schmunk42** [comment]
I am not really convinced that this is problematic, if someone could come up with a test-case, I'd be glad to review it. The code from @githubjeka would also throw an error, if you forget to import the namespace.

Moreover, not to be picky here, but PSR-2 is not about autoloading or namespaces, [PSR-0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md) and [PSR-4](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md) are.
In PSR-0 and PSR-4 it is required to have a vendor namespace and you can freely choose your sub-namespaces, please correct me if I am wrong.

**Comment by Faryshta** [comment]
ok i am closing this issue then

**Comment by schmunk42** [comment]
Please reopen or create a new one, if you're running into errors.
