### ISSUE TITLE
Extraction admin-lte from packagist.org

### ISSUE THREAD

**Issue by githubjeka** [dmstr/yii2-adminlte-asset#39]
Now uses `"bower-asset/admin-lte": "~2.0",` 

It is redundant, since the probability of collisions  is approximately zero.

I propose to change on https://packagist.org/packages/almasaeed2010/adminlte

```
"almasaeed2010/adminlte": "~2.0",
```

This will save the life of ~10 seconds :palm_tree: :sunny: :surfer:

**Comment by schmunk42** [comment]
> This will save the life of ~10 seconds

You mean because the fxp asset plugin download is so slow?
I don't mind the change, if it's BC.

**Comment by Faryshta** [comment]
the only change would be to change the asset bundle

    public $sourcePath = '@bower/admin-lte/dist';

to

    public $sourcePath = '@vendor/almasaeed2010/admin-lte/dist';

and you would get bc compatibility

**Comment by Faryshta** [comment]
i created a pr #42 to fix this. i tested it and it works bc compatible.

**Comment by githubjeka** [comment]
Thanks
