### ISSUE TITLE
Wrong package namespace

### ISSUE THREAD

**Issue by freezy-sk** [dmstr/yii2-adminlte-asset#44]
Hi
What about changing this package to follow best practice in package namespacing and following rule `VendorName\PackageName\ClassName`?
Of course this will be a breaking change, so package version should be bumped to 3.0.
I you agree, I can make PR.

**Comment by schmunk42** [comment]
Already discussed here: https://github.com/dmstr/yii2-adminlte-asset/issues/38

Please let me know, if you run into problems.
