### ISSUE TITLE
Version constraint for rmrevin/yii2-fontawesome

### ISSUE THREAD

**Issue by schmunk42** [dmstr/yii2-adminlte-asset#47]
Follow up from https://github.com/dmstr/yii2-adminlte-asset/pull/45#issuecomment-102975396

**Comment by Faryshta** [comment]
this one is difficult. @rmrevin what do you think about it?

**Comment by rmrevin** [comment]
I do not quite understand what is at stake.
All versions in the `2.*` branch backward compatible. Since only the new functionality and bug fixes appear.
Once the break backward compatibility (which is unlikely), it will change the version in the `3.*`

**Comment by Faryshta** [comment]
Then we should change

        "rmrevin/yii2-fontawesome": "2.9.*"

to

        "rmrevin/yii2-fontawesome": "2.*"

**Comment by rmrevin** [comment]
I think nothing bad will happen.
