### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by vc7deo** [dmstr/yii2-adminlte-asset#5]
getting **Undefined index: appName** error

 in C:\wamp\www\yii2-advanced-api\vendor\dmstr\yii2-adminlte-asset\phundament4\layouts\main.php
![error](https://cloud.githubusercontent.com/assets/8149102/5227146/7853ed26-771d-11e4-828e-d5a75556f17c.jpg)

**Comment by ivanrayhan12** [comment]
i can fixed the problem 
$config = [
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'cYY7xTnsn1bahaxL8Pxeg_YgYOAmfoF0',
        ],

     'view' => [
         'theme' => [
             'pathMap' => [
                    '@app/views' => '@vendor/dmstr/yii2-adminlte-asset/example-views/yiisoft/yii2-app'
                     ],
                ],
            ],
        ],
    ];


], put after view.
``
