### ISSUE TITLE
Break css of body class

### ISSUE THREAD

**Issue by githubjeka** [dmstr/yii2-adminlte-asset#52]
https://github.com/dmstr/yii2-adminlte-asset/blob/a4cb13cb4e2faa416ec284249c79ffa4e798bb28/helpers/AdminLteHelper.php#L16

```php
 public static function skinClass()
    {
        /** @var \dmstr\web\AdminLteAsset $bundle */
        $bundle = Yii::$app->assetManager->getBundle('dmstr\web\AdminLteAsset');
        return $bundle->skin;
    }
```

When `$bundle->skin` is `_all-skins` by default then `skinClass()` return wrong css of body class.

Need return correct css class, e.g. `skin-black`

**Comment by schmunk42** [comment]
It's because by default `_all-skins` are registered. The helper works only in conjunction with selecting a skin. Which skin should the helper return, if you've selected none? :)

Do you think this can be covered by documentation?

**Comment by githubjeka** [comment]
Opps... I want send PR , but update directly.
I added note.
