### ISSUE TITLE
Class 'dmstr\web\AdminLteAsset' not found

### ISSUE THREAD

**Issue by georgejr** [dmstr/yii2-adminlte-asset#53]
On windows XAMPP I got this. On Debian works fine the same code
Any ideas?

My code:
`
use yii\helpers\Html;
use dmstr\web\AdminLteAsset as AdminLteAsset;

/* @var $this \yii\web\View */
/* @var $content string */

if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }
   AdminLteAsset::register($this);`

**Comment by schmunk42** [comment]
What's the error on XAMPP?

**Comment by georgejr** [comment]
Class 'dmstr\web\AdminLteAsset' not found

**Comment by schmunk42** [comment]
In which line, stacktrace, etc ....

**Comment by kevinobama** [comment]
Class 'dmstr\web\AdminLteAsset' not found

**Comment by axis161** [comment]
why and how is this closed ?
