### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Nasreddine** [dmstr/yii2-adminlte-asset#56]
I want to know if your template supports right to left layout ?

**Comment by githubjeka** [comment]
No. Only right

**Comment by mazurva** [comment]
@Nasreddine almasaeed2010/AdminLTE not support RTL, but RTL support forks, eg: https://github.com/Yellowen/AdminLTE-rtl

**Comment by maxodrom** [comment]
You can see about RTL support here: https://github.com/almasaeed2010/AdminLTE/issues/469
