### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by ulasbinici** [dmstr/yii2-adminlte-asset#58]
when i tried to intall im getting this message 

[UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*"  

i'v already updated composer "selfupdate"

**Comment by schmunk42** [comment]
I noticed that also, you need to update the composer-asset-plugin, see also https://github.com/francoispluchino/composer-asset-plugin/issues/129

    composer global update

I am also updating the phundament/php Docker images at the moment.
