### ISSUE TITLE
login page problem

### ISSUE THREAD

**Issue by logsanctuary** [dmstr/yii2-adminlte-asset#59]
Hello,

The dashboard is ok in my yii2 app but i have a problem with the login page. I think they can load the necessary asset css or js because i can see the icon or the style of the normal login page.
Could you explain me the procedure to have a correct login page ?
Do i use the $this->layout = '//main-login' ? i dont understant where i put it ...

BR, 
Thank you

**Comment by githubjeka** [comment]
use the code `$this->layout = '//main-login';` in your controller.

E.g.

```php
class SiteController extends Controller
{
 public function actionLogin()
{
        $this->layout = '//main-login';
        //...
}
```

**Comment by logsanctuary** [comment]
Hi,

i tried this and i add this code in my site controller but with no result. 

please look at it this screenshot :

![capture du 2015-08-31 20 49 47](https://cloud.githubusercontent.com/assets/9827015/9587329/57cdfa22-5022-11e5-9430-edf2316a97e4.png)

**Comment by githubjeka** [comment]
There is any errors in debug of browser?

**Comment by logsanctuary** [comment]
there are no errors in debug of browser , all url is HTTP 200 ok (css, js, etc.)

the code source of the page :

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-param" content="_csrf">
    <meta name="csrf-token" content="sample">
    <title>Sign In</title>
    <link href="/start/assets/dcb22c9e/css/font-awesome.min.css" rel="stylesheet">
<link href="/start/assets/99a1b917/css/AdminLTE.min.css" rel="stylesheet">
<link href="/start/assets/99a1b917/css/skins/_all-skins.min.css" rel="stylesheet"></head>
<body class="login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Admin</b>LTE</a>
    </div>
    
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form id="login-form" action="/start/site/login" method="post" role="form">
<input type="hidden" name="_csrf" value="sample">
        <div class="form-group has-feedback field-loginform-username required">
<input type="text" id="loginform-username" class="form-control" name="LoginForm[username]" placeholder="Utilisateur"><span class='glyphicon glyphicon-envelope form-control-feedback'></span>
<p class="help-block help-block-error"></p>
</div>
        <div class="form-group has-feedback field-loginform-password required">
<input type="password" id="loginform-password" class="form-control" name="LoginForm[password]" placeholder="Mot de passe"><span class='glyphicon glyphicon-lock form-control-feedback'></span>
<p class="help-block help-block-error"></p>
</div>
        <div class="row">
            <div class="col-xs-8">
                <div class="form-group field-loginform-rememberme">
<div class="checkbox">
<label for="loginform-rememberme">
<input type="hidden" name="LoginForm[rememberMe]" value="0"><input type="checkbox" id="loginform-rememberme" name="LoginForm[rememberMe]" value="1" checked>
Se souvenir de moi
</label>
<p class="help-block help-block-error"></p>
</div>
</div>            </div>
            
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat" name="login-button">Sign in</button>            </div>
            
        </div>
        </form>
        <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in
                using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign
                in using Google+</a>
        </div>
        
        <a href="#">I forgot my password</a><br>
        <a href="register.html" class="text-center">Register a new membership</a>
    </div>
    
</div>
<script src="/start/assets/38031859/jquery.js"></script>
<script src="/start/assets/2ff44fd1/yii.js"></script>
<script src="/start/assets/2ff44fd1/yii.activeForm.js"></script>
<script src="/start/assets/c3ef115d/js/bootstrap.js"></script>
<script src="/start/assets/99a1b917/js/app.min.js"></script>
<script type="text/javascript">jQuery(document).ready(function () {
jQuery('#login-form').yiiActiveForm([], []);
});</script></body>
</html>

**Comment by githubjeka** [comment]
May be problem in `_all-skins.min.css` . Please choose one skin. https://github.com/dmstr/yii2-adminlte-asset#skins

**Comment by githubjeka** [comment]
Hmmm ... I don't see `<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">`
You should register  'yii\bootstrap\BootstrapAsset', in your AppAsset.php :
https://github.com/githubjeka/yii2-app-advanced/blob/master/backend/assets/AppAsset.php#L25

**Comment by logsanctuary** [comment]
there are no change, i add the skin and the bootstrapasset, i test with the advanced temple but it is the same think

```html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-param" content="_csrf">
    <meta name="csrf-token" content="">
    <title>Sign In</title>
    <link href="/start/assets/dcb22c9e/css/font-awesome.min.css" rel="stylesheet">
<link href="/start/assets/99a1b917/css/AdminLTE.min.css" rel="stylesheet">
<link href="/start/assets/99a1b917/css/skins/skin-blue.min.css" rel="stylesheet"></head>
<body class="skin-blue login-page">


    
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Admin</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form id="login-form" action="/start/site/login" method="post" role="form">
<input type="hidden" name="_csrf" value="">
        <div class="form-group has-feedback field-loginform-username required">

<input type="text" id="loginform-username" class="form-control" name="LoginForm[username]" placeholder="Utilisateur"><span class='glyphicon glyphicon-envelope form-control-feedback'></span>

<p class="help-block help-block-error"></p>
</div>
        <div class="form-group has-feedback field-loginform-password required">

<input type="password" id="loginform-password" class="form-control" name="LoginForm[password]" placeholder="Mot de passe"><span class='glyphicon glyphicon-lock form-control-feedback'></span>

<p class="help-block help-block-error"></p>
</div>
        <div class="row">
            <div class="col-xs-8">
                <div class="form-group field-loginform-rememberme">
<div class="checkbox">
<label for="loginform-rememberme">
<input type="hidden" name="LoginForm[rememberMe]" value="0"><input type="checkbox" id="loginform-rememberme" name="LoginForm[rememberMe]" value="1" checked>
Se souvenir de moi
</label>
<p class="help-block help-block-error"></p>

</div>
</div>            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat" name="login-button">Sign in</button>            </div>
            <!-- /.col -->
        </div>


        </form>
        <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in
                using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign
                in using Google+</a>
        </div>
        <!-- /.social-auth-links -->

        <a href="#">I forgot my password</a><br>
        <a href="register.html" class="text-center">Register a new membership</a>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

<script src="/start/assets/38031859/jquery.js"></script>
<script src="/start/assets/2ff44fd1/yii.js"></script>
<script src="/start/assets/2ff44fd1/yii.activeForm.js"></script>
<script src="/start/assets/c3ef115d/js/bootstrap.js"></script>
<script src="/start/assets/99a1b917/js/app.min.js"></script>
<script type="text/javascript">jQuery(document).ready(function () {
jQuery('#login-form').yiiActiveForm([], []);
});</script></body>
</html>
```

**Comment by schmunk42** [comment]
What does the asset section in the debug panel say?

Is there also no `'yii\bootstrap\BootstrapAsset => false` eg. in AssetManager config?

**Comment by logsanctuary** [comment]
ok you are the best . the explanation :
```html
        'assetManager' => [
            'bundles' => [
                // we will use bootstrap css from our theme
                'yii\bootstrap\BootstrapAsset' => [
                   'css' => [], // do not use yii default one
                ],
```

**Comment by schmunk42** [comment]
:smile:

**Comment by reidelgp** [comment]
Hello, I have a problem with the login, my situation is as follows: adminlte logout does not eject me from the system to the login window, I must do it 2 times, the 1st time I logout but it stays in the inside of the application (always logout) and the second time I logout if it takes me to the login window, to solve this problem use the following code:
    'on beforeAction' => function ($event) {
        $action = \Yii::$app->requestedRoute;
        if ( (!\Yii::$app->user->identity) && strpos($action, "site/login") === false ) {
            header("Location:".\Yii::$app->urlManager->createAbsoluteUrl("site/login"));
            exit();
        }
    },

I did this in the web.php file, in the $config array. It works well, to detect that there is no one with login takes me to the sale of login but it shows me 2 user form. Could you help me with this problem please? Sorry me english.

![adminlte yii2](https://user-images.githubusercontent.com/44037243/48640519-ede64680-e9a4-11e8-8b6f-53888369aeb3.png)

**Comment by reidelgp** [comment]
and I need 'on beforeAction' because I have to be verifying certain sessions that have not been lost before saving any data in the database. I just realized that the login window is giving me a console error, probably because it shows 2 form, instead of one, this is the error it gives me:
Uncaught TypeError: Cannot read property 'querySelector' of null
    at showToolbar (index.php?r=site%2Flogin:496)
    at Object.success (index.php?r=site%2Flogin:487)
    at XMLHttpRequest.xhr.onreadystatechange (index.php?r=site%2Flogin:446)
