### ISSUE TITLE
Depend on BootstrapAsset

### ISSUE THREAD

**Issue by githubjeka** [dmstr/yii2-adminlte-asset#60]
Perhaps we need to register `'yii\bootstrap\BootstrapAsset',` in out AdminLteAsset.php ?

Related #59 login page problem

**Comment by mazurva** [comment]
I'm sure. I can create a pull request.

**Comment by schmunk42** [comment]
But we need to make sure that bootstrap css is not included twice.

**Comment by mazurva** [comment]
Yii2 self remove duplicate dependencies

**Comment by schmunk42** [comment]
Is [this](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/AdminLTE.css) only additional  CSS or does it include bootstrap also?

**Comment by githubjeka** [comment]
No
### With bootsrap.css
![image](https://cloud.githubusercontent.com/assets/874234/9636678/68711948-51a5-11e5-8748-218df66f11f9.png)
----------
### Without bootsrap.css
![image](https://cloud.githubusercontent.com/assets/874234/9636701/89be70b4-51a5-11e5-92d0-24232eb1e242.png)

**Comment by schmunk42** [comment]
Then it's fine I think, just double-checked this, since many CSS themes provide a custom bootstrap version.
