### ISSUE TITLE
Wrong menu

### ISSUE THREAD

**Issue by githubjeka** [dmstr/yii2-adminlte-asset#63]
After PR https://github.com/dmstr/yii2-adminlte-asset/pull/61
people complain:
![image](https://cloud.githubusercontent.com/assets/874234/9780738/4d8b1e08-5795-11e5-95a9-42e467f40cbd.png)

**Comment by schmunk42** [comment]
Can you post the Menu widget code?

**Comment by githubjeka** [comment]
Yeah, i will fix https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/yiisoft/yii2-app/layouts/left.php

**Comment by schmunk42** [comment]
I merged this, but still had the issue you mentioned with a yii2 application.

This would be my fix:
![bildschirmfoto 2015-09-10 um 08 34 51](https://cloud.githubusercontent.com/assets/649031/9781645/eeeacd88-5796-11e5-971b-d47bcad5ff3d.png)

Isn't the class still missing for you?

**Comment by schmunk42** [comment]
I pushed this (together with a testing stack) on a branch: https://github.com/dmstr/yii2-adminlte-asset/commit/c53daa8a8081aede93e9df88316bb25f45609566

Let me know if I should merge this with master.

**Comment by githubjeka** [comment]
Yes. It need

**Comment by schmunk42** [comment]
Ok, it's pushed on master.
Could you check if it works and get back to me, I'll create a tag if it's OK.

**Comment by githubjeka** [comment]
Bug in https://github.com/dmstr/yii2-adminlte-asset/blob/master/widgets/Menu.php#L36

**Comment by githubjeka** [comment]
For 
```php
 ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
```

![image](https://cloud.githubusercontent.com/assets/874234/9787052/d08d40e2-57c7-11e5-86ae-6b57b726e419.png)

**Comment by githubjeka** [comment]
@schmunk42 All fine.

**Comment by schmunk42** [comment]
Great :)
