### ISSUE TITLE
Menu widget - isItemActive buggy

### ISSUE THREAD

**Issue by Boco10** [dmstr/yii2-adminlte-asset#64]
Hello.

I've two url : 
/frontend/web/index.php/individual/manage
/frontend/web/index.php/individual/upload

<pre>

$items [] = ['label' => Yii::t('app','Register Car'), 'url' => ['individual/upload']];
$items [] = ['label' => Yii::t('app','Manage Cars'), 'url' => ['individual/manage']];

echo  dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu'],
                'items' => $items,
            ]
);</pre>

No matter which one i click both of them 'li' has the active tag on. I've deleted the complete isItemActive method, now its working fine.

#61

**Comment by schmunk42** [comment]
Could you try to specify an absolute route?

    'url' => ['/individual/upload']];

**Comment by Boco10** [comment]
Same result

**Comment by schmunk42** [comment]
@kongoon @githubjeka @eluhr @deacix Any idea?

**Comment by schmunk42** [comment]
I have a workaround for this issue, please see https://github.com/dmstr/yii2-adminlte-asset/commit/e5a24e376388928dc3fa85a6d25b7e1dc8af24f3

Any better ideas? I think I will not work if you have just a different action.

**Comment by githubjeka** [comment]
It's(e5a24e3) working for yii-app now.

**Comment by schmunk42** [comment]
available in 2.2.2
