### ISSUE TITLE
Get fonts.googleapis.com TIME_OUT

### ISSUE THREAD

**Issue by Yannyezixin** [dmstr/yii2-adminlte-asset#67]
I can't connect to fonts.googleapis.com 

so I want to know how I remove 

      @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);

from adminLTE.min.css

**Comment by githubjeka** [comment]
You want replace Source+Sans+Pro: on your font ?
Just rewrite `yii2-adminlte-asset/web/AdminLteAsset.php`

**Comment by Yannyezixin** [comment]
Thanks
I Just remove 
        @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);
from vender/almasaeed2010/adminlte/dist/css/adminLTE.css

**Comment by githubjeka** [comment]
All will return after update.

**Comment by imlonghao** [comment]
Try:
```
@import url(https://fonts.geekzu.org/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);
```
