### ISSUE TITLE
how to remove left-sidebar

### ISSUE THREAD

**Issue by markquee** [dmstr/yii2-adminlte-asset#72]
how to remove the left-sidebar .. i successfully remove the content of sidebar but still two columns

**Comment by githubjeka** [comment]
Just delete this code https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/yiisoft/yii2-app/layouts/main.php#L48

**Comment by markquee** [comment]
about that if you remove the left the only thing that remove is the content of the sidebar and not really the sidebar itself.. it is still has a column of a sidebar... so let me revise the questions how to or by default the sidebar is hide but on toggle it shows .. here  is the options that adminlte list to me..   sidebarToggleSelector: "[data-toggle='offcanvas']".. I have a vague idea probably bootstrapswitch but i dont know how or do you have some better idea where the sidebar only show when its click the button
