### ISSUE TITLE
Composer install Error

### ISSUE THREAD

**Issue by mrbighokage** [dmstr/yii2-adminlte-asset#75]
[RuntimeException]
  Could not load package rmrevin/yii2-fontawesome in http://packagist.org: [UnexpectedValueException] Could not parse version constraint v4.1.*: Invalid version string "v4.1.*
  "

  [UnexpectedValueException]
  Could not parse version constraint v4.1.*: Invalid version string "v4.1.*"

**Comment by mrbighokage** [comment]
Whot is it "Invalid version string v4.1" this bad version!

**Comment by schmunk42** [comment]
Which command do you issue?
I can't reproduce this.

**Comment by mrbighokage** [comment]
composer update
or composer install --preffer...

for reproduse error install this progect 
https://github.com/mrbighokage/yii2-start-app-template

**Comment by githubjeka** [comment]
I had someone asked this week about it already.

**Comment by githubjeka** [comment]
To fix it: need update `fxp/composer-asset-plugin:1.1.0` to `1.1.1`

**Comment by mrbighokage** [comment]
Thank you

**Comment by mrbighokage** [comment]
Write to README.md fxp/composer-asset-plugin version

**Comment by githubjeka** [comment]
Done. Thanks.
