### ISSUE TITLE
Add {linkOptions} to template

### ISSUE THREAD

**Issue by maxxer** [dmstr/yii2-adminlte-asset#78]
```php
public $linkTemplate = '<a href="{url}"{linkOptions}>{icon} {label}</a>';
```
so that it could be possible to add `target="_blank"`

**Comment by githubjeka** [comment]
Do you have Pull Request?  ;)

**Comment by maxxer** [comment]
I'm about to do that but... My plan would be to rewrite most of the `renderItem` method, using `Html::a($label, $url, $linkOptions)` instead of the template. Given this consideration I'd like to better understand your intentions with the current implementation.

1. why you added the *{link}* item in template? Isn't it supposed to always exist, otherwise it's a label template?
1. the whole `$linkTemplate` shuold move away for something like `$linkLabelTemplate` which could template the link text. Is there any other reason why you left the whole `<a href...` stuff customizable? Is there anything else in menu items other than *a* tags?

The result would be a more generic implementation, allowing to specify *target* and also *data-method* tags to the link (which is almost always required for logout links).

What do you think?

**Comment by maxxer** [comment]
[This](https://github.com/maxxer/yii2-adminlte-asset/commit/17dbbbe5d69a48ba1e4a7de17ead51a08d37fff5) is what I meant ;)

**Comment by schmunk42** [comment]
@maxxer That looks promising, I will try to review it more deeply in the next days. Thank you!

**Comment by schmunk42** [comment]
> Is there anything else in menu items other than a tags?

I don't know if it is supported right now, but what's about separators and dividers?

**Comment by maxxer** [comment]
@Quexer69 what's the purpose of making another PR *mostly* identical to an existing one?

**Comment by maxxer** [comment]
@schmunk42 I see @Quexer69 handled this in [his patch](https://github.com/Quexer69/yii2-adminlte-asset/commit/5baec31b8461a14c1b0ce81f24615dab7761c049?diff=unified#diff-00135f692cda799af409bc4edd66a674R46).

Other than this they look the same to me

**Comment by schmunk42** [comment]
We were discussing this a few minutes ago. We're not trying to steal your credits ;)

You are right about the changes. 
I was just thinking about the fact that this change requires a 3.x version according to semver.

Would there be a sane way to make it bc-compatible?

CC: @githubjeka Any thoughts?

**Comment by githubjeka** [comment]
You can refactor `renderItem($item)` to 

```php
protected function renderItem($item) {
    if (!isset($item['url'])) {
           // return dropdown logic 
    }

    // return default logic 
}
```

**Comment by githubjeka** [comment]
@schmunk42 PR's is bad in current form. 

@maxxer Use `template` attribute of `\yii\widgets\Menu::$items` to add `target`
```php
                   [
                        'label' => 'Login',
                        'icon' => 'fa fa-user',
                        'url' => ['site/login'],
                        'visible' => Yii::$app->user->isGuest,
                        'template' => '<a href="{url}" target="_blank">{icon} {label}</a>'
                    ],
```

It default way by Yii2.
