### ISSUE TITLE
add linkOptions support to dmstr\widgets\Menu

### ISSUE THREAD

**Issue by coobic** [dmstr/yii2-adminlte-asset#80]
Can you add support for linkOptions to Menu widget?

Code described here:
https://toster.ru/q/204731

It`s very usefull option for create LogOut link in Menu (not in navbar, etc).

**Comment by githubjeka** [comment]
https://github.com/dmstr/yii2-adminlte-asset/issues/78#issuecomment-170099442

**Comment by coobic** [comment]
I`m refactor template, but this solution is also good, many thanks for link.

**Comment by Alfiriny** [comment]
Thanks! githubjeka

**Comment by sigitpurnomo7680** [comment]
Thank you.
Great coding.

**Comment by shubhamrastogi1994** [comment]
Add {linkOptions} in template 
 public $linkTemplate = '<a href="{url}" {linkOptions}>{icon} {label}</a>';
and Add in renderItem in $replacements array 
'{linkOptions}' => isset($item['linkOptions'])?http_build_query($item['linkOptions'],null, " "):'',
and now we can use linkOptions in this widget.
