### ISSUE TITLE
Plugins in admilte charts

### ISSUE THREAD

**Issue by markquee** [dmstr/yii2-adminlte-asset#83]
Hi!.. I have trouble in integrating the plugins here under vendor\almasaeed2010\adminlte\plugins like charts.. Im ok about using the adminLTE skins co'z of this Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist'); now how to declare the plugins under the @vendor/almasaeed2010/adminlte/plugins?

**Comment by githubjeka** [comment]
Create your AssetBundle with 
```php
 public $sourcePath = '@vendor/almasaeed2010/adminlte/plugins/chartjs/';
```
