### ISSUE TITLE
level 2 sub menu url problem

### ISSUE THREAD

**Issue by vladjap** [dmstr/yii2-adminlte-asset#87]
Hi, i have problem with url in sub sub menu. When i put url in lvl 2 sub menu it points to domain.com/controller/action instead of domain.com/backend/web/index.php?r=controller/action. In lvl 1 sub menu it is working fine. Any solution?

**Comment by githubjeka** [comment]
Can you show the code to reproduce.

**Comment by vladjap** [comment]
In menu widget:
`<?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu'],
                'items' => [
                    ['label' => 'Menu Total Koš', 'options' => ['class' => 'header']],
                    [
                        'label' => 'Users',
                        'icon' => 'fa fa-users',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Users', 'icon' => 'fa fa-reorder', 'url' => ['/user/admin/index'],],//this is ok
                            ['label' => 'Roles', 'icon' => 'fa fa-cog', 'url' => ['/rbac/role/index'],],//this is ok
                            ['label' => 'Permissions', 'icon' => 'fa fa-cogs', 'url' => ['/rbac/permission/index'],],//this is ok
                            [
                                'label' => 'Create',
                                'icon' => 'fa fa-plus',
                                'url' => '#',
                                'items' => [
//                                    ['label' => 'New user', 'icon' => 'fa fa-bug', 'url' => '/user/admin/create',],
                                    ['label' => 'New user', 'icon' => 'fa fa-bug', 'url' =>  Yii::$app->getUrlManager()->createAbsoluteUrl('/user/admin/create')],//this is also ok
                                    ['label' => 'New role', 'icon' => 'fa fa-bug', 'url' => '/rbac/role/create',],//this is not ok
                                    ['label' => 'New permission', 'icon' => 'fa fa-bug', 'url' => '/rbac/permission/create',],//this is not ok

                                ],
                            ],
                        ],
                    ],
                    ['label' => 'News categories', 'icon' => 'fa fa-folder-open', 'url' => ['/news-category']],
                    [
                        'label' => 'Posts',
                        'icon' => 'fa fa-archive',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Posts', 'icon' => 'fa fa-reorder', 'url' => ['/posts'],],
                            ['label' => 'New post', 'icon' => 'fa fa-plus', 'url' => ['/posts/create'],],
                        ],
                    ],
                    ['label' => 'Gii', 'icon' => 'fa fa-file-code-o', 'url' => ['/gii']],
                    ['label' => 'Debug', 'icon' => 'fa fa-dashboard', 'url' => ['/debug']],
                    ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
                ],
            ]
        ) ?>`

![bug](https://cloud.githubusercontent.com/assets/8859535/16034978/72738c0a-31c9-11e6-8d54-5f4871ed34a3.png)

when i create absolute url it wokrs as it should, but i think it should work without absolute url as it is in level 1 submenu.

**Comment by githubjeka** [comment]
You should use array to set URL. Because string is just string without conversions. If you use a array then UrlManager conversions the array to URL by his rules from config

```
['label' => 'New role', 'icon' => 'fa fa-bug', 'url' => ['/rbac/role/create'],],
```

**Comment by vladjap** [comment]
thank you, i think you should change it in example from
` ['label' => 'Level Three', 'icon' => 'fa fa-circle-o', 'url' => '#',], `
to 
`['label' => 'Level Three', 'icon' => 'fa fa-circle-o', 'url' => ['#'],],`

**Comment by vladjap** [comment]
oh, i am sorry, it should not... i should try it before i said :)

**Comment by githubjeka** [comment]
`'url' => '#'` is url of current page and # anchor (id or name html element)
`url' => ['#']` is something strange
