### ISSUE TITLE
Error in name styles with multilevel icons, so angle icon is aligned to bottom

### ISSUE THREAD

**Issue by kvush** [dmstr/yii2-adminlte-asset#88]
Multi level icon align to bottom instead to center. I guess error in dmstr\widgets\Menu
 `protected function renderItem($item)
    {
        if(isset($item['items'])) {
            $labelTemplate = '<a href="{url}">{label} <i class="fa fa-angle-left pull-right"></i></a>';
            $linkTemplate = '<a href="{url}">{icon} {label} <i class="fa fa-angle-left pull-right"></i></a>';
        }
        else {...}`

class pull-right should be change to pull-right-container, so full class name for "i" tag should be
 `<i class="fa fa-angle-left pull-right-container"></i>`

**Comment by githubjeka** [comment]
Can you try the <small> tag? https://github.com/dmstr/yii2-adminlte-asset#left-sidebar-menu---widget-menu

Native AdminLTE html code is:
```html
       <li>
          <a href="pages/widgets.html">
            <i class="fa fa-th"></i> <span>Widgets</span>
            <small class="label pull-right bg-green">new</small>
          </a>
        </li>
```

**Comment by kvush** [comment]
No, there is no problem with label, i speak about multilevel item. If menu grouped to multi level then \dmstr\widgets\Menu automaticaly add icon `fa fa-angle-left` adjust to right by pull-right class. But in AdminLTE source files have only pull-right-container. And i had changed $labelTemplate and $linkTemplate on the renderItem function and it is now working correctly

**Comment by githubjeka** [comment]
May be PR?
