### ISSUE TITLE
got problem when changing skin

### ISSUE THREAD

**Issue by jokernaut** [dmstr/yii2-adminlte-asset#97]
![skin](https://cloud.githubusercontent.com/assets/21050359/17850883/7a3ee96a-6889-11e6-8ec0-9414aeeed71e.JPG)
This is what I got when I'm trying to change the skin via config aside from blue

**Comment by Quexer69** [comment]
Where and how do you set the skin ?

Could you paste the config and error?

**Comment by jokernaut** [comment]
I just put the skin config under components at config/web.php just like the readme said.

I'm using yii 2.9.0

**Comment by jokernaut** [comment]
Thank you, it works wonders
