### ISSUE TITLE
Black Flashs while switching the pages

### ISSUE THREAD

**Issue by jgtb** [dmstr/yii2-adminlte-asset#98]
When i switch one page using the AdminLTE Theme i get a BLACK FLASH

For every page

**Comment by githubjeka** [comment]
Need more details...

**Comment by jgtb** [comment]
Whenever page change appears black flashes, for example: 
I am on page /site/about and i click to the page /site/contact 
in the middle appears the black flash

**Comment by githubjeka** [comment]
Magic. Can you provide screenshots?

**Comment by jgtb** [comment]
https://sendvid.com/5kkxitsp

**Comment by githubjeka** [comment]
It's problem AdminLTE. 
Try at https://almsaeedstudio.com/themes/AdminLTE/pages/examples/blank.html
Just you have black color for body style, native AdminLte - white. 
For a quick fix you can set the color of the body is the same as the content.
Closed. Follow to issue at [AdminLte repo](https://github.com/almasaeed2010/AdminLTE/issues/1191).

**Comment by githubjeka** [comment]
Fixed in AdminLTE

**Comment by jgtb** [comment]
do you know the source of this? couldn't find it.

**Comment by githubjeka** [comment]
Ask [here](https://github.com/almasaeed2010/AdminLTE/issues/1191) . I think the issue fixed in new version.
