### ISSUE TITLE
Multi-level menu on the style of fa-angle-left do not change after clicking

### ISSUE THREAD

**Issue by phpyii** [dmstr/yii2-adminlte-asset#99]

**Comment by githubjeka** [comment]
Please provide your code.
This code is working by default:
```php
                     [
                        'label' => 'Files',
                        'icon' => 'fa fa-file',
                        'url' => '#',                       
                        'items' => [
                            [
                                'label' => 'Public',
                                'url' => ['/file'],
                                'icon' => 'fa fa-file',
                            ],
                            [
                                'label' => 'Archive',
                                'url' => ['/binary/index'],
                                'icon' => 'fa fa-file',
                            ],
                        ],
                    ],
```

**Comment by phpyii** [comment]
@githubjeka  有个人也遇到这个问题了 https://github.com/almasaeed2010/AdminLTE/issues/1145

**Comment by schmunk42** [comment]
Should we use more restrictive composer constraints for AdminLTE?

**Comment by githubjeka** [comment]
Any example?

**Comment by schmunk42** [comment]
Based on that comment: https://github.com/almasaeed2010/AdminLTE/issues/1145#issuecomment-248038006
> Same issue without multilevel since upgrading to 2.3.6 from 2.3.3.

We could create a `asset-2.3.4` which requires `AdminLTE ~2.0 && <=2.3.3`
And also tag a release `asset-2.4.0` which requires  `AdminLTE ~2.0 && >=2.3.4`

**Comment by githubjeka** [comment]
Not worth doing

**Comment by schmunk42** [comment]
Agreed. So basically the fix is 

    composer require "almasaeed2010/adminlte:2.3.3"

to fix the version of the AdminLTE package in your project.
